// finalassignment.h
// Generated by decompiling finalassignment
// using Reko decompiler version 0.9.0.0.

/*
// Equivalence classes ////////////
Eq_1: (struct "Globals" (107D0 int32 dw107D0) (107D4 int32 dw107D4) (107F8 word32 dw107F8) (107FC word32 dw107FC) (10800 (ptr32 code) ptr10800) (10830 word32 dw10830) (10834 word32 dw10834) (10838 (ptr32 code) ptr10838) (10860 (ptr32 byte) ptr10860) (10D68 word32 dw10D68) (11220 (ptr32 (arr word64)) ptr11220) (11274 (ptr32 (arr word64)) ptr11274) (112C8 Eq_498 t112C8) (112D0 Eq_498 t112D0) (11550 (ptr32 Eq_523) ptr11550) (11720 Eq_498 t11720) (117F8 real32 r117F8) (118F4 (ptr32 (ptr32 (ptr32 (ptr32 code)))) ptr118F4) (11934 (ptr32 (ptr32 (ptr32 (ptr32 (ptr32 code))))) ptr11934) (11938 int32 dw11938) (2200C (ptr32 code) ptr2200C) (22010 (ptr32 code) ptr22010) (22014 (ptr32 code) ptr22014) (22018 (ptr32 code) ptr22018) (2201C (ptr32 code) ptr2201C) (22020 (ptr32 code) ptr22020) (22024 (ptr32 code) ptr22024) (22028 (ptr32 code) ptr22028) (2202C (ptr32 code) ptr2202C) (22030 (ptr32 code) ptr22030) (22034 (ptr32 code) ptr22034) (22038 (ptr32 code) ptr22038) (2203C (ptr32 code) ptr2203C) (22040 (ptr32 code) ptr22040) (22044 (ptr32 code) ptr22044) (22048 (ptr32 code) ptr22048) (2204C (ptr32 code) ptr2204C) (22050 (ptr32 code) ptr22050) (22054 (ptr32 code) ptr22054) (22058 (ptr32 code) ptr22058) (2205C (ptr32 code) ptr2205C))
	globals_t (in globals : (ptr32 (struct "Globals")))
Eq_3: (fn (ptr32 code) ((ptr32 code)))
	T_3 (in call_weak_fn : ptr32)
	T_4 (in signature of call_weak_fn : void)
	T_54 (in call_weak_fn : ptr32)
Eq_47: (fn void ())
	T_47 (in fn000106F4 : ptr32)
	T_48 (in signature of fn000106F4 : void)
Eq_50: (fn void ())
	T_50 (in fn0001076C : ptr32)
	T_51 (in signature of fn0001076C : void)
Eq_115: (fn void ((ptr32 code)))
	T_115 (in deregister_tm_clones : ptr32)
	T_116 (in signature of deregister_tm_clones : void)
Eq_123: (fn void ((ptr32 code)))
	T_123 (in register_tm_clones : ptr32)
	T_124 (in signature of register_tm_clones : void)
Eq_126: (fn void ())
	T_126 (in echoSensorCleanUp : ptr32)
	T_127 (in signature of echoSensorCleanUp : void)
Eq_129: (fn void ())
	T_129 (in lineSensorsCleanUp : ptr32)
	T_130 (in signature of lineSensorsCleanUp : void)
Eq_132: (fn void ())
	T_132 (in motorsCleanUp : ptr32)
	T_133 (in signature of motorsCleanUp : void)
Eq_135: (fn void ())
	T_135 (in fn00010718 : ptr32)
	T_136 (in signature of fn00010718 : void)
	T_283 (in fn00010718 : ptr32)
	T_556 (in fn00010718 : ptr32)
Eq_138: (fn void (word32))
	T_138 (in setUp : ptr32)
	T_139 (in signature of setUp : void)
	T_238 (in setUp : ptr32)
Eq_143: (fn void (word32))
	T_143 (in lineSensorSetup : ptr32)
	T_144 (in signature of lineSensorSetup : void)
Eq_146: (fn word32 (word32))
	T_146 (in motorsSet : ptr32)
	T_147 (in signature of motorsSet : void)
Eq_151: (fn void ())
	T_151 (in echoSensorSet : ptr32)
	T_152 (in signature of echoSensorSet : void)
Eq_154: (fn void ())
	T_154 (in speedSensorSet : ptr32)
	T_155 (in signature of speedSensorSet : void)
Eq_158: (fn void ())
	T_158 (in fn000106E8 : ptr32)
	T_159 (in signature of fn000106E8 : void)
	T_186 (in fn000106E8 : ptr32)
	T_554 (in fn000106E8 : ptr32)
	T_630 (in fn000106E8 : ptr32)
Eq_161: (fn void ())
	T_161 (in fn000106D0 : ptr32)
	T_162 (in signature of fn000106D0 : void)
	T_167 (in fn000106D0 : ptr32)
	T_174 (in fn000106D0 : ptr32)
	T_180 (in fn000106D0 : ptr32)
	T_216 (in fn000106D0 : ptr32)
	T_220 (in fn000106D0 : ptr32)
Eq_171: (fn void ())
	T_171 (in fn00010688 : ptr32)
	T_172 (in signature of fn00010688 : void)
	T_178 (in fn00010688 : ptr32)
	T_184 (in fn00010688 : ptr32)
	T_197 (in fn00010688 : ptr32)
	T_224 (in fn00010688 : ptr32)
	T_232 (in fn00010688 : ptr32)
	T_533 (in fn00010688 : ptr32)
	T_623 (in fn00010688 : ptr32)
Eq_188: (fn void ())
	T_188 (in fn00010754 : ptr32)
	T_189 (in signature of fn00010754 : void)
	T_191 (in fn00010754 : ptr32)
	T_193 (in fn00010754 : ptr32)
	T_195 (in fn00010754 : ptr32)
	T_226 (in fn00010754 : ptr32)
	T_228 (in fn00010754 : ptr32)
Eq_201: (fn void ())
	T_201 (in decreaseMotorPowerToZero : ptr32)
	T_202 (in signature of decreaseMotorPowerToZero : void)
Eq_204: (fn void ())
	T_204 (in readDistance : ptr32)
	T_205 (in signature of readDistance : void)
	T_230 (in readDistance : ptr32)
Eq_207: (fn word32 ())
	T_207 (in isObjectInFront : ptr32)
	T_208 (in signature of isObjectInFront : void)
Eq_235: (fn void ())
	T_235 (in fn000106AC : ptr32)
	T_236 (in signature of fn000106AC : void)
Eq_241: (fn void (word32))
	T_241 (in moveforward : ptr32)
	T_242 (in signature of moveforward : void)
Eq_244: (fn void ())
	T_244 (in fn00010730 : ptr32)
	T_245 (in signature of fn00010730 : void)
	T_454 (in fn00010730 : ptr32)
	T_544 (in fn00010730 : ptr32)
	T_580 (in fn00010730 : ptr32)
Eq_249: (fn void ())
	T_249 (in fn00010724 : ptr32)
	T_250 (in signature of fn00010724 : void)
	T_252 (in fn00010724 : ptr32)
	T_254 (in fn00010724 : ptr32)
	T_256 (in fn00010724 : ptr32)
	T_258 (in fn00010724 : ptr32)
	T_260 (in fn00010724 : ptr32)
	T_262 (in fn00010724 : ptr32)
	T_264 (in fn00010724 : ptr32)
	T_266 (in fn00010724 : ptr32)
	T_268 (in fn00010724 : ptr32)
	T_270 (in fn00010724 : ptr32)
	T_272 (in fn00010724 : ptr32)
	T_456 (in fn00010724 : ptr32)
	T_458 (in fn00010724 : ptr32)
	T_460 (in fn00010724 : ptr32)
	T_462 (in fn00010724 : ptr32)
	T_548 (in fn00010724 : ptr32)
	T_550 (in fn00010724 : ptr32)
	T_552 (in fn00010724 : ptr32)
	T_582 (in fn00010724 : ptr32)
	T_584 (in fn00010724 : ptr32)
Eq_274: (fn void ())
	T_274 (in fn00010760 : ptr32)
	T_275 (in signature of fn00010760 : void)
	T_285 (in fn00010760 : ptr32)
	T_292 (in fn00010760 : ptr32)
	T_299 (in fn00010760 : ptr32)
Eq_280: (fn void ())
	T_280 (in fn000106C4 : ptr32)
	T_281 (in signature of fn000106C4 : void)
	T_290 (in fn000106C4 : ptr32)
	T_297 (in fn000106C4 : ptr32)
	T_306 (in fn000106C4 : ptr32)
	T_310 (in fn000106C4 : ptr32)
Eq_313: (fn void ())
	T_313 (in fn000106B8 : ptr32)
	T_314 (in signature of fn000106B8 : void)
	T_321 (in fn000106B8 : ptr32)
	T_323 (in fn000106B8 : ptr32)
	T_325 (in fn000106B8 : ptr32)
	T_327 (in fn000106B8 : ptr32)
	T_329 (in fn000106B8 : ptr32)
	T_331 (in fn000106B8 : ptr32)
	T_333 (in fn000106B8 : ptr32)
	T_335 (in fn000106B8 : ptr32)
	T_351 (in fn000106B8 : ptr32)
	T_353 (in fn000106B8 : ptr32)
	T_355 (in fn000106B8 : ptr32)
	T_538 (in fn000106B8 : ptr32)
	T_540 (in fn000106B8 : ptr32)
	T_542 (in fn000106B8 : ptr32)
	T_586 (in fn000106B8 : ptr32)
	T_588 (in fn000106B8 : ptr32)
	T_595 (in fn000106B8 : ptr32)
	T_599 (in fn000106B8 : ptr32)
	T_674 (in fn000106B8 : ptr32)
	T_676 (in fn000106B8 : ptr32)
Eq_316: (fn void ())
	T_316 (in fn0001073C : ptr32)
	T_317 (in signature of fn0001073C : void)
	T_341 (in fn0001073C : ptr32)
	T_343 (in fn0001073C : ptr32)
	T_345 (in fn0001073C : ptr32)
	T_347 (in fn0001073C : ptr32)
Eq_366: (fn void (word32))
	T_366 (in motorMove : ptr32)
	T_367 (in signature of motorMove : void)
	T_372 (in motorMove : ptr32)
	T_377 (in motorMove : ptr32)
	T_380 (in motorMove : ptr32)
	T_392 (in motorMove : ptr32)
	T_397 (in motorMove : ptr32)
	T_402 (in motorMove : ptr32)
	T_405 (in motorMove : ptr32)
	T_408 (in motorMove : ptr32)
	T_411 (in motorMove : ptr32)
	T_414 (in motorMove : ptr32)
	T_417 (in motorMove : ptr32)
	T_434 (in motorMove : ptr32)
	T_437 (in motorMove : ptr32)
	T_440 (in motorMove : ptr32)
	T_443 (in motorMove : ptr32)
Eq_420: (fn void ())
	T_420 (in fn000106DC : ptr32)
	T_421 (in signature of fn000106DC : void)
	T_432 (in fn000106DC : ptr32)
	T_597 (in fn000106DC : ptr32)
Eq_423: (fn void ())
	T_423 (in motorStop : ptr32)
	T_424 (in signature of motorStop : void)
	T_426 (in motorStop : ptr32)
	T_428 (in motorStop : ptr32)
	T_430 (in motorStop : ptr32)
	T_446 (in motorStop : ptr32)
	T_448 (in motorStop : ptr32)
	T_450 (in motorStop : ptr32)
	T_452 (in motorStop : ptr32)
Eq_472: (fn void ())
	T_472 (in fn000106A0 : ptr32)
	T_473 (in signature of fn000106A0 : void)
Eq_481: (fn void ())
	T_481 (in fn0001067C : ptr32)
	T_482 (in signature of fn0001067C : void)
Eq_484: (fn (ptr64 Eq_489) (Eq_486))
	T_484 (in __vmov_f64 : ptr32)
	T_485 (in signature of __vmov_f64 : void)
	T_493 (in __vmov_f64 : ptr32)
	T_494 (in __vmov_f64 : ptr32)
	T_625 (in __vmov_f64 : ptr32)
	T_637 (in __vmov_f64 : ptr32)
	T_638 (in __vmov_f64 : ptr32)
	T_651 (in __vmov_f64 : ptr32)
	T_652 (in __vmov_f64 : ptr32)
	T_664 (in __vmov_f64 : ptr32)
	T_665 (in __vmov_f64 : ptr32)
Eq_486: (union "Eq_486" (real64 u0) (word128 u1) (word32 u2))
	T_486 (in  : word64)
	T_488 (in (word64) SLICE(r3_r2_19, word32, 0) : word64)
	T_490 (in __vmov_f64((word64) (word32) r3_r2_19)() : word32)
	T_492 (in d0 : Eq_486)
	T_497 (in  : word64)
	T_499 (in (real64) r0 : real64)
	T_507 (in __vmul_f64((real64) r0, globals->t112C8) / __vmul_f64(d0, globals->t112D0) : real64)
	T_509 (in __vmov_f64(__vmul_f64((real64) r0, globals->t112C8) / __vmul_f64(d0, globals->t112D0))() : word32)
	T_511 (in __vmov_f64(__vmov_f64(__vmul_f64((real64) r0, globals->t112C8) / __vmul_f64(d0, globals->t112D0))())() : word32)
	T_590 (in d0 : Eq_486)
	T_601 (in q0 : Eq_486)
	T_627 (in (word64) SLICE(d7_43, word32, 0) : word64)
	T_629 (in __vmov_f64((word64) (word32) d7_43)() : word32)
	T_642 (in SLICE(getTime(), word64, 0) : word64)
	T_644 (in __vmov_f64((word64) getTime())() : word32)
	T_646 (in __vmov_f64(__vmov_f64((word64) getTime())())() : word32)
	T_655 (in SLICE(getTime(), word64, 0) : word64)
	T_657 (in __vmov_f64((word64) getTime())() : word32)
	T_659 (in __vmov_f64(__vmov_f64((word64) getTime())())() : word32)
	T_668 (in SLICE(getTime(), word64, 0) : word64)
	T_670 (in __vmov_f64((word64) getTime())() : word32)
	T_672 (in __vmov_f64(__vmov_f64((word64) getTime())())() : word32)
Eq_489: (fn Eq_486 ())
	T_489 (in __vmov_f64((word64) (word32) r3_r2_19) : word64)
	T_508 (in __vmov_f64(__vmul_f64((real64) r0, globals->t112C8) / __vmul_f64(d0, globals->t112D0)) : word64)
	T_510 (in __vmov_f64(__vmov_f64(__vmul_f64((real64) r0, globals->t112C8) / __vmul_f64(d0, globals->t112D0))()) : word64)
	T_628 (in __vmov_f64((word64) (word32) d7_43) : word64)
	T_643 (in __vmov_f64((word64) getTime()) : word64)
	T_645 (in __vmov_f64(__vmov_f64((word64) getTime())()) : word64)
	T_656 (in __vmov_f64((word64) getTime()) : word64)
	T_658 (in __vmov_f64(__vmov_f64((word64) getTime())()) : word64)
	T_669 (in __vmov_f64((word64) getTime()) : word64)
	T_671 (in __vmov_f64(__vmov_f64((word64) getTime())()) : word64)
Eq_495: (fn (arr real64 1) (Eq_486, Eq_498))
	T_495 (in __vmul_f64 : ptr32)
	T_496 (in signature of __vmul_f64 : void)
	T_503 (in __vmul_f64 : ptr32)
	T_591 (in __vmul_f64 : ptr32)
Eq_498: (union "Eq_498" (word64 u0) (word32 u1))
	T_498 (in  : word64)
	T_501 (in Mem10[0x000112C8:word32] : word32)
	T_505 (in Mem10[0x000112D0:word32] : word32)
	T_593 (in Mem9[0x00011720:word32] : word32)
Eq_512: (fn void ())
	T_512 (in fn00010748 : ptr32)
	T_513 (in signature of fn00010748 : void)
Eq_515: (fn void ())
	T_515 (in readPulses : ptr32)
	T_516 (in signature of readPulses : void)
Eq_518: (fn (arr word64 1) (word64, word64))
	T_518 (in __vadd_f64 : ptr32)
	T_519 (in signature of __vadd_f64 : void)
Eq_523: (struct "Eq_523" (0 word64 qw0000) (10 word64 qw0010))
	T_523 (in Mem13[0x00011550:word32] : word32)
	T_528 (in Mem13[0x00011550:word32] : word32)
Eq_535: (fn void ())
	T_535 (in fn00010694 : ptr32)
	T_536 (in signature of fn00010694 : void)
	T_559 (in fn00010694 : ptr32)
	T_566 (in fn00010694 : ptr32)
	T_570 (in fn00010694 : ptr32)
	T_602 (in fn00010694 : ptr32)
	T_610 (in fn00010694 : ptr32)
Eq_607: (fn void ())
	T_607 (in fn0001070C : ptr32)
	T_608 (in signature of fn0001070C : void)
	T_615 (in fn0001070C : ptr32)
Eq_632: (fn void ())
	T_632 (in prepareTrigger : ptr32)
	T_633 (in signature of prepareTrigger : void)
	T_648 (in prepareTrigger : ptr32)
	T_661 (in prepareTrigger : ptr32)
Eq_635: (fn void (Eq_486))
	T_635 (in calculateDistance : ptr32)
	T_636 (in signature of calculateDistance : void)
	T_650 (in calculateDistance : ptr32)
	T_663 (in calculateDistance : ptr32)
Eq_639: (fn word128 ())
	T_639 (in getTime : ptr32)
	T_640 (in signature of getTime : void)
	T_653 (in getTime : ptr32)
	T_666 (in getTime : ptr32)
Eq_692: (union "Eq_692" (int32 u0) (ptr32 u1))
	T_692 (in 0x000118F4 + Mem18[0x00011934:word32] : word32)
Eq_698: (fn word32 ((ptr32 code)))
	T_698 (in _init : ptr32)
	T_699 (in signature of _init : void)
// Type Variables ////////////
globals_t: (in globals : (ptr32 (struct "Globals")))
  Class: Eq_1
  DataType: (ptr32 Eq_1)
  OrigDataType: (ptr32 (struct "Globals"))
T_2: (in lr : (ptr32 code))
  Class: Eq_2
  DataType: (ptr32 code)
  OrigDataType: word32
T_3: (in call_weak_fn : ptr32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (fn T_6 (T_2)))
T_4: (in signature of call_weak_fn : void)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: 
T_5: (in lr : (ptr32 code))
  Class: Eq_2
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_6: (in call_weak_fn(lr) : word32)
  Class: Eq_2
  DataType: (ptr32 code)
  OrigDataType: word32
T_7: (in 0002200C : ptr32)
  Class: Eq_7
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_8 t0000)))
T_8: (in Mem0[0x0002200C:word32] : word32)
  Class: Eq_8
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_9: (in 00022010 : ptr32)
  Class: Eq_9
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_10 t0000)))
T_10: (in Mem0[0x00022010:word32] : word32)
  Class: Eq_10
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_11: (in 00022014 : ptr32)
  Class: Eq_11
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_12 t0000)))
T_12: (in Mem0[0x00022014:word32] : word32)
  Class: Eq_12
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_13: (in 00022018 : ptr32)
  Class: Eq_13
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_14 t0000)))
T_14: (in Mem0[0x00022018:word32] : word32)
  Class: Eq_14
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_15: (in 0002201C : ptr32)
  Class: Eq_15
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_16 t0000)))
T_16: (in Mem0[0x0002201C:word32] : word32)
  Class: Eq_16
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_17: (in 00022020 : ptr32)
  Class: Eq_17
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_18 t0000)))
T_18: (in Mem0[0x00022020:word32] : word32)
  Class: Eq_18
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_19: (in 00022024 : ptr32)
  Class: Eq_19
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_20 t0000)))
T_20: (in Mem0[0x00022024:word32] : word32)
  Class: Eq_20
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_21: (in 00022028 : ptr32)
  Class: Eq_21
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_22 t0000)))
T_22: (in Mem0[0x00022028:word32] : word32)
  Class: Eq_22
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_23: (in 0002202C : ptr32)
  Class: Eq_23
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_24 t0000)))
T_24: (in Mem0[0x0002202C:word32] : word32)
  Class: Eq_24
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_25: (in 00022030 : ptr32)
  Class: Eq_25
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_26 t0000)))
T_26: (in Mem0[0x00022030:word32] : word32)
  Class: Eq_26
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_27: (in 00022034 : ptr32)
  Class: Eq_27
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_28 t0000)))
T_28: (in Mem0[0x00022034:word32] : word32)
  Class: Eq_28
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_29: (in 0002203C : ptr32)
  Class: Eq_29
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_30 t0000)))
T_30: (in Mem0[0x0002203C:word32] : word32)
  Class: Eq_30
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_31: (in 00022040 : ptr32)
  Class: Eq_31
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_32 t0000)))
T_32: (in Mem0[0x00022040:word32] : word32)
  Class: Eq_32
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_33: (in 00022044 : ptr32)
  Class: Eq_33
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_34 t0000)))
T_34: (in Mem0[0x00022044:word32] : word32)
  Class: Eq_34
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_35: (in 00022048 : ptr32)
  Class: Eq_35
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_36 t0000)))
T_36: (in Mem0[0x00022048:word32] : word32)
  Class: Eq_36
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_37: (in 0002204C : ptr32)
  Class: Eq_37
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_38 t0000)))
T_38: (in Mem0[0x0002204C:word32] : word32)
  Class: Eq_38
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_39: (in 00022050 : ptr32)
  Class: Eq_39
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_40 t0000)))
T_40: (in Mem0[0x00022050:word32] : word32)
  Class: Eq_40
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_41: (in 00022054 : ptr32)
  Class: Eq_41
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_42 t0000)))
T_42: (in Mem0[0x00022054:word32] : word32)
  Class: Eq_42
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_43: (in 00022058 : ptr32)
  Class: Eq_43
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_44 t0000)))
T_44: (in Mem0[0x00022058:word32] : word32)
  Class: Eq_44
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_45: (in 0002205C : ptr32)
  Class: Eq_45
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_46 t0000)))
T_46: (in Mem0[0x0002205C:word32] : word32)
  Class: Eq_46
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_47: (in fn000106F4 : ptr32)
  Class: Eq_47
  DataType: (ptr32 Eq_47)
  OrigDataType: (ptr32 (fn T_49 ()))
T_48: (in signature of fn000106F4 : void)
  Class: Eq_47
  DataType: (ptr32 Eq_47)
  OrigDataType: 
T_49: (in fn000106F4() : void)
  Class: Eq_49
  DataType: void
  OrigDataType: void
T_50: (in fn0001076C : ptr32)
  Class: Eq_50
  DataType: (ptr32 Eq_50)
  OrigDataType: (ptr32 (fn T_52 ()))
T_51: (in signature of fn0001076C : void)
  Class: Eq_50
  DataType: (ptr32 Eq_50)
  OrigDataType: 
T_52: (in fn0001076C() : void)
  Class: Eq_52
  DataType: void
  OrigDataType: void
T_53: (in Z : bool)
  Class: Eq_53
  DataType: bool
  OrigDataType: bool
T_54: (in call_weak_fn : ptr32)
  Class: Eq_3
  DataType: (ptr32 Eq_3)
  OrigDataType: (ptr32 (fn T_56 (T_55)))
T_55: (in 0x00000000 : word32)
  Class: Eq_2
  DataType: (ptr32 code)
  OrigDataType: word32
T_56: (in call_weak_fn(null) : word32)
  Class: Eq_2
  DataType: (ptr32 code)
  OrigDataType: word32
T_57: (in 000107C4 : ptr32)
  Class: Eq_57
  DataType: ptr32
  OrigDataType: ptr32
T_58: (in 000107D0 : ptr32)
  Class: Eq_58
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_59 t0000)))
T_59: (in Mem0[0x000107D0:word32] : word32)
  Class: Eq_59
  DataType: int32
  OrigDataType: int32
T_60: (in 0x000107C4 + globals->dw107D0 : word32)
  Class: Eq_60
  DataType: ptr32
  OrigDataType: ptr32
T_61: (in 000107D4 : ptr32)
  Class: Eq_61
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_62 t0000)))
T_62: (in Mem0[0x000107D4:word32] : word32)
  Class: Eq_62
  DataType: int32
  OrigDataType: int32
T_63: (in 0x000107C4 + globals->dw107D0 + globals->dw107D4 : word32)
  Class: Eq_63
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_64 t0000)))
T_64: (in Mem0[0x000107C4 + Mem0[0x000107D0:word32] + Mem0[0x000107D4:word32]:word32] : word32)
  Class: Eq_64
  DataType: word32
  OrigDataType: word32
T_65: (in 0x00000000 : word32)
  Class: Eq_64
  DataType: word32
  OrigDataType: word32
T_66: (in 0x000107C4 + globals->dw107D0 + globals->dw107D4 != 0x00000000 : bool)
  Class: Eq_66
  DataType: bool
  OrigDataType: bool
T_67: (in lr_23 : (ptr32 code))
  Class: Eq_2
  DataType: (ptr32 code)
  OrigDataType: word32
T_68: (in lr_16 : (ptr32 code))
  Class: Eq_2
  DataType: (ptr32 code)
  OrigDataType: word32
T_69: (in 00022038 : ptr32)
  Class: Eq_69
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_70 t0000)))
T_70: (in Mem0[0x00022038:word32] : word32)
  Class: Eq_70
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_71: (in lr : (ptr32 code))
  Class: Eq_71
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_72: (in 000107FC : ptr32)
  Class: Eq_72
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_73 t0000)))
T_73: (in Mem0[0x000107FC:word32] : word32)
  Class: Eq_73
  DataType: word32
  OrigDataType: word32
T_74: (in 000107F8 : ptr32)
  Class: Eq_74
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_75 t0000)))
T_75: (in Mem0[0x000107F8:word32] : word32)
  Class: Eq_73
  DataType: word32
  OrigDataType: word32
T_76: (in globals->dw107FC != globals->dw107F8 : bool)
  Class: Eq_76
  DataType: bool
  OrigDataType: bool
T_77: (in r3_8 : (ptr32 code))
  Class: Eq_77
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_78: (in 00010800 : ptr32)
  Class: Eq_78
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_79 t0000)))
T_79: (in Mem0[0x00010800:word32] : word32)
  Class: Eq_77
  DataType: (ptr32 code)
  OrigDataType: word32
T_80: (in 0x00000000 : word32)
  Class: Eq_77
  DataType: (ptr32 code)
  OrigDataType: word32
T_81: (in r3_8 != null : bool)
  Class: Eq_81
  DataType: bool
  OrigDataType: bool
T_82: (in lr_15 : word32)
  Class: Eq_82
  DataType: word32
  OrigDataType: word32
T_83: (in lr : (ptr32 code))
  Class: Eq_83
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_84: (in r1_6 : int32)
  Class: Eq_84
  DataType: int32
  OrigDataType: int32
T_85: (in 00010834 : ptr32)
  Class: Eq_85
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_86 t0000)))
T_86: (in Mem0[0x00010834:word32] : word32)
  Class: Eq_86
  DataType: word32
  OrigDataType: word32
T_87: (in 00010830 : ptr32)
  Class: Eq_87
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_88 t0000)))
T_88: (in Mem0[0x00010830:word32] : word32)
  Class: Eq_88
  DataType: word32
  OrigDataType: word32
T_89: (in globals->dw10834 - globals->dw10830 : word32)
  Class: Eq_84
  DataType: int32
  OrigDataType: word32
T_90: (in 2 : int32)
  Class: Eq_90
  DataType: int32
  OrigDataType: int32
T_91: (in r1_6 >> 2 : word32)
  Class: Eq_91
  DataType: int32
  OrigDataType: int32
T_92: (in 33 : int32)
  Class: Eq_92
  DataType: int32
  OrigDataType: int32
T_93: (in r1_6 >> 33 : word32)
  Class: Eq_93
  DataType: int32
  OrigDataType: int32
T_94: (in (r1_6 >> 2) + (r1_6 >> 33) : word32)
  Class: Eq_94
  DataType: int32
  OrigDataType: int32
T_95: (in 1 : int32)
  Class: Eq_95
  DataType: int32
  OrigDataType: int32
T_96: (in (r1_6 >> 2) + (r1_6 >> 33) >> 1 : word32)
  Class: Eq_96
  DataType: int32
  OrigDataType: int32
T_97: (in 0x00000000 : word32)
  Class: Eq_96
  DataType: int32
  OrigDataType: word32
T_98: (in (r1_6 >> 2) + (r1_6 >> 33) >> 1 != 0x00000000 : bool)
  Class: Eq_98
  DataType: bool
  OrigDataType: bool
T_99: (in r3_12 : (ptr32 code))
  Class: Eq_99
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_100: (in 00010838 : ptr32)
  Class: Eq_100
  DataType: (ptr32 (ptr32 code))
  OrigDataType: (ptr32 (struct (0 T_101 t0000)))
T_101: (in Mem0[0x00010838:word32] : word32)
  Class: Eq_99
  DataType: (ptr32 code)
  OrigDataType: word32
T_102: (in 0x00000000 : word32)
  Class: Eq_99
  DataType: (ptr32 code)
  OrigDataType: word32
T_103: (in r3_12 != null : bool)
  Class: Eq_103
  DataType: bool
  OrigDataType: bool
T_104: (in lr_18 : word32)
  Class: Eq_104
  DataType: word32
  OrigDataType: word32
T_105: (in lr : (ptr32 code))
  Class: Eq_71
  DataType: (ptr32 code)
  OrigDataType: word32
T_106: (in r4_8 : (ptr32 byte))
  Class: Eq_106
  DataType: (ptr32 byte)
  OrigDataType: (ptr32 (struct (0 T_111 t0000)))
T_107: (in 00010860 : ptr32)
  Class: Eq_107
  DataType: (ptr32 (ptr32 byte))
  OrigDataType: (ptr32 (struct (0 T_108 t0000)))
T_108: (in Mem6[0x00010860:word32] : word32)
  Class: Eq_106
  DataType: (ptr32 byte)
  OrigDataType: word32
T_109: (in 0x00000000 : word32)
  Class: Eq_109
  DataType: word32
  OrigDataType: word32
T_110: (in r4_8 + 0x00000000 : word32)
  Class: Eq_110
  DataType: word32
  OrigDataType: word32
T_111: (in Mem6[r4_8 + 0x00000000:byte] : byte)
  Class: Eq_111
  DataType: byte
  OrigDataType: byte
T_112: (in (word32) Mem6[r4_8 + 0x00000000:byte] : word32)
  Class: Eq_112
  DataType: word32
  OrigDataType: word32
T_113: (in 0x00000000 : word32)
  Class: Eq_112
  DataType: word32
  OrigDataType: word32
T_114: (in (word32) *r4_8 == 0x00000000 : bool)
  Class: Eq_114
  DataType: bool
  OrigDataType: bool
T_115: (in deregister_tm_clones : ptr32)
  Class: Eq_115
  DataType: (ptr32 Eq_115)
  OrigDataType: (ptr32 (fn T_117 (T_105)))
T_116: (in signature of deregister_tm_clones : void)
  Class: Eq_115
  DataType: (ptr32 Eq_115)
  OrigDataType: 
T_117: (in deregister_tm_clones(lr) : void)
  Class: Eq_117
  DataType: void
  OrigDataType: void
T_118: (in 0x01 : byte)
  Class: Eq_111
  DataType: byte
  OrigDataType: byte
T_119: (in 0x00000000 : word32)
  Class: Eq_119
  DataType: word32
  OrigDataType: word32
T_120: (in r4_8 + 0x00000000 : word32)
  Class: Eq_120
  DataType: (ptr32 byte)
  OrigDataType: (ptr32 byte)
T_121: (in Mem21[r4_8 + 0x00000000:byte] : byte)
  Class: Eq_111
  DataType: byte
  OrigDataType: byte
T_122: (in lr : (ptr32 code))
  Class: Eq_83
  DataType: (ptr32 code)
  OrigDataType: word32
T_123: (in register_tm_clones : ptr32)
  Class: Eq_123
  DataType: (ptr32 Eq_123)
  OrigDataType: (ptr32 (fn T_125 (T_122)))
T_124: (in signature of register_tm_clones : void)
  Class: Eq_123
  DataType: (ptr32 Eq_123)
  OrigDataType: 
T_125: (in register_tm_clones(lr) : void)
  Class: Eq_125
  DataType: void
  OrigDataType: void
T_126: (in echoSensorCleanUp : ptr32)
  Class: Eq_126
  DataType: (ptr32 Eq_126)
  OrigDataType: (ptr32 (fn T_128 ()))
T_127: (in signature of echoSensorCleanUp : void)
  Class: Eq_126
  DataType: (ptr32 Eq_126)
  OrigDataType: 
T_128: (in echoSensorCleanUp() : void)
  Class: Eq_128
  DataType: void
  OrigDataType: void
T_129: (in lineSensorsCleanUp : ptr32)
  Class: Eq_129
  DataType: (ptr32 Eq_129)
  OrigDataType: (ptr32 (fn T_131 ()))
T_130: (in signature of lineSensorsCleanUp : void)
  Class: Eq_129
  DataType: (ptr32 Eq_129)
  OrigDataType: 
T_131: (in lineSensorsCleanUp() : void)
  Class: Eq_131
  DataType: void
  OrigDataType: void
T_132: (in motorsCleanUp : ptr32)
  Class: Eq_132
  DataType: (ptr32 Eq_132)
  OrigDataType: (ptr32 (fn T_134 ()))
T_133: (in signature of motorsCleanUp : void)
  Class: Eq_132
  DataType: (ptr32 Eq_132)
  OrigDataType: 
T_134: (in motorsCleanUp() : void)
  Class: Eq_134
  DataType: void
  OrigDataType: void
T_135: (in fn00010718 : ptr32)
  Class: Eq_135
  DataType: (ptr32 Eq_135)
  OrigDataType: (ptr32 (fn T_137 ()))
T_136: (in signature of fn00010718 : void)
  Class: Eq_135
  DataType: (ptr32 Eq_135)
  OrigDataType: 
T_137: (in fn00010718() : void)
  Class: Eq_137
  DataType: void
  OrigDataType: void
T_138: (in setUp : ptr32)
  Class: Eq_138
  DataType: (ptr32 Eq_138)
  OrigDataType: (ptr32 (fn T_142 (T_141)))
T_139: (in signature of setUp : void)
  Class: Eq_138
  DataType: (ptr32 Eq_138)
  OrigDataType: 
T_140: (in r0 : word32)
  Class: Eq_140
  DataType: word32
  OrigDataType: word32
T_141: (in 0x00000000 : word32)
  Class: Eq_140
  DataType: word32
  OrigDataType: word32
T_142: (in setUp(0x00000000) : void)
  Class: Eq_142
  DataType: void
  OrigDataType: void
T_143: (in lineSensorSetup : ptr32)
  Class: Eq_143
  DataType: (ptr32 Eq_143)
  OrigDataType: (ptr32 (fn T_150 (T_149)))
T_144: (in signature of lineSensorSetup : void)
  Class: Eq_143
  DataType: (ptr32 Eq_143)
  OrigDataType: 
T_145: (in r0 : word32)
  Class: Eq_145
  DataType: word32
  OrigDataType: word32
T_146: (in motorsSet : ptr32)
  Class: Eq_146
  DataType: (ptr32 Eq_146)
  OrigDataType: (ptr32 (fn T_149 (T_140)))
T_147: (in signature of motorsSet : void)
  Class: Eq_146
  DataType: (ptr32 Eq_146)
  OrigDataType: 
T_148: (in r0 : word32)
  Class: Eq_140
  DataType: word32
  OrigDataType: word32
T_149: (in motorsSet(r0) : word32)
  Class: Eq_145
  DataType: word32
  OrigDataType: word32
T_150: (in lineSensorSetup(motorsSet(r0)) : void)
  Class: Eq_150
  DataType: void
  OrigDataType: void
T_151: (in echoSensorSet : ptr32)
  Class: Eq_151
  DataType: (ptr32 Eq_151)
  OrigDataType: (ptr32 (fn T_153 ()))
T_152: (in signature of echoSensorSet : void)
  Class: Eq_151
  DataType: (ptr32 Eq_151)
  OrigDataType: 
T_153: (in echoSensorSet() : void)
  Class: Eq_153
  DataType: void
  OrigDataType: void
T_154: (in speedSensorSet : ptr32)
  Class: Eq_154
  DataType: (ptr32 Eq_154)
  OrigDataType: (ptr32 (fn T_156 ()))
T_155: (in signature of speedSensorSet : void)
  Class: Eq_154
  DataType: (ptr32 Eq_154)
  OrigDataType: 
T_156: (in speedSensorSet() : void)
  Class: Eq_156
  DataType: void
  OrigDataType: void
T_157: (in fpscr : word32)
  Class: Eq_157
  DataType: word32
  OrigDataType: word32
T_158: (in fn000106E8 : ptr32)
  Class: Eq_158
  DataType: (ptr32 Eq_158)
  OrigDataType: (ptr32 (fn T_160 ()))
T_159: (in signature of fn000106E8 : void)
  Class: Eq_158
  DataType: (ptr32 Eq_158)
  OrigDataType: 
T_160: (in fn000106E8() : void)
  Class: Eq_160
  DataType: void
  OrigDataType: void
T_161: (in fn000106D0 : ptr32)
  Class: Eq_161
  DataType: (ptr32 Eq_161)
  OrigDataType: (ptr32 (fn T_163 ()))
T_162: (in signature of fn000106D0 : void)
  Class: Eq_161
  DataType: (ptr32 Eq_161)
  OrigDataType: 
T_163: (in fn000106D0() : void)
  Class: Eq_163
  DataType: void
  OrigDataType: void
T_164: (in fp : ptr32)
  Class: Eq_164
  DataType: ptr32
  OrigDataType: ptr32
T_165: (in 0x0000005C : word32)
  Class: Eq_164
  DataType: ptr32
  OrigDataType: word32
T_166: (in fp == 0x0000005C : bool)
  Class: Eq_166
  DataType: bool
  OrigDataType: bool
T_167: (in fn000106D0 : ptr32)
  Class: Eq_161
  DataType: (ptr32 Eq_161)
  OrigDataType: (ptr32 (fn T_168 ()))
T_168: (in fn000106D0() : void)
  Class: Eq_163
  DataType: void
  OrigDataType: void
T_169: (in 0x00000060 : word32)
  Class: Eq_164
  DataType: ptr32
  OrigDataType: word32
T_170: (in fp == 0x00000060 : bool)
  Class: Eq_170
  DataType: bool
  OrigDataType: bool
T_171: (in fn00010688 : ptr32)
  Class: Eq_171
  DataType: (ptr32 Eq_171)
  OrigDataType: (ptr32 (fn T_173 ()))
T_172: (in signature of fn00010688 : void)
  Class: Eq_171
  DataType: (ptr32 Eq_171)
  OrigDataType: 
T_173: (in fn00010688() : void)
  Class: Eq_173
  DataType: void
  OrigDataType: void
T_174: (in fn000106D0 : ptr32)
  Class: Eq_161
  DataType: (ptr32 Eq_161)
  OrigDataType: (ptr32 (fn T_175 ()))
T_175: (in fn000106D0() : void)
  Class: Eq_163
  DataType: void
  OrigDataType: void
T_176: (in 0x00000064 : word32)
  Class: Eq_164
  DataType: ptr32
  OrigDataType: word32
T_177: (in fp == 0x00000064 : bool)
  Class: Eq_177
  DataType: bool
  OrigDataType: bool
T_178: (in fn00010688 : ptr32)
  Class: Eq_171
  DataType: (ptr32 Eq_171)
  OrigDataType: (ptr32 (fn T_179 ()))
T_179: (in fn00010688() : void)
  Class: Eq_173
  DataType: void
  OrigDataType: void
T_180: (in fn000106D0 : ptr32)
  Class: Eq_161
  DataType: (ptr32 Eq_161)
  OrigDataType: (ptr32 (fn T_181 ()))
T_181: (in fn000106D0() : void)
  Class: Eq_163
  DataType: void
  OrigDataType: void
T_182: (in 0x00000068 : word32)
  Class: Eq_164
  DataType: ptr32
  OrigDataType: word32
T_183: (in fp == 0x00000068 : bool)
  Class: Eq_183
  DataType: bool
  OrigDataType: bool
T_184: (in fn00010688 : ptr32)
  Class: Eq_171
  DataType: (ptr32 Eq_171)
  OrigDataType: (ptr32 (fn T_185 ()))
T_185: (in fn00010688() : void)
  Class: Eq_173
  DataType: void
  OrigDataType: void
T_186: (in fn000106E8 : ptr32)
  Class: Eq_158
  DataType: (ptr32 Eq_158)
  OrigDataType: (ptr32 (fn T_187 ()))
T_187: (in fn000106E8() : void)
  Class: Eq_160
  DataType: void
  OrigDataType: void
T_188: (in fn00010754 : ptr32)
  Class: Eq_188
  DataType: (ptr32 Eq_188)
  OrigDataType: (ptr32 (fn T_190 ()))
T_189: (in signature of fn00010754 : void)
  Class: Eq_188
  DataType: (ptr32 Eq_188)
  OrigDataType: 
T_190: (in fn00010754() : void)
  Class: Eq_190
  DataType: void
  OrigDataType: void
T_191: (in fn00010754 : ptr32)
  Class: Eq_188
  DataType: (ptr32 Eq_188)
  OrigDataType: (ptr32 (fn T_192 ()))
T_192: (in fn00010754() : void)
  Class: Eq_190
  DataType: void
  OrigDataType: void
T_193: (in fn00010754 : ptr32)
  Class: Eq_188
  DataType: (ptr32 Eq_188)
  OrigDataType: (ptr32 (fn T_194 ()))
T_194: (in fn00010754() : void)
  Class: Eq_190
  DataType: void
  OrigDataType: void
T_195: (in fn00010754 : ptr32)
  Class: Eq_188
  DataType: (ptr32 Eq_188)
  OrigDataType: (ptr32 (fn T_196 ()))
T_196: (in fn00010754() : void)
  Class: Eq_190
  DataType: void
  OrigDataType: void
T_197: (in fn00010688 : ptr32)
  Class: Eq_171
  DataType: (ptr32 Eq_171)
  OrigDataType: (ptr32 (fn T_198 ()))
T_198: (in fn00010688() : void)
  Class: Eq_173
  DataType: void
  OrigDataType: void
T_199: (in SLICE(fpscr, bool, 2) : bool)
  Class: Eq_199
  DataType: bool
  OrigDataType: bool
T_200: (in Test(LE,SLICE(fpscr, bool, 2)) : bool)
  Class: Eq_200
  DataType: bool
  OrigDataType: bool
T_201: (in decreaseMotorPowerToZero : ptr32)
  Class: Eq_201
  DataType: (ptr32 Eq_201)
  OrigDataType: (ptr32 (fn T_203 ()))
T_202: (in signature of decreaseMotorPowerToZero : void)
  Class: Eq_201
  DataType: (ptr32 Eq_201)
  OrigDataType: 
T_203: (in decreaseMotorPowerToZero() : void)
  Class: Eq_203
  DataType: void
  OrigDataType: void
T_204: (in readDistance : ptr32)
  Class: Eq_204
  DataType: (ptr32 Eq_204)
  OrigDataType: (ptr32 (fn T_206 ()))
T_205: (in signature of readDistance : void)
  Class: Eq_204
  DataType: (ptr32 Eq_204)
  OrigDataType: 
T_206: (in readDistance() : void)
  Class: Eq_206
  DataType: void
  OrigDataType: void
T_207: (in isObjectInFront : ptr32)
  Class: Eq_207
  DataType: (ptr32 Eq_207)
  OrigDataType: (ptr32 (fn T_209 ()))
T_208: (in signature of isObjectInFront : void)
  Class: Eq_207
  DataType: (ptr32 Eq_207)
  OrigDataType: 
T_209: (in isObjectInFront() : word32)
  Class: Eq_209
  DataType: word32
  OrigDataType: word32
T_210: (in 0x00000001 : word32)
  Class: Eq_210
  DataType: word32
  OrigDataType: word32
T_211: (in isObjectInFront() ^ 0x00000001 : word32)
  Class: Eq_211
  DataType: ui32
  OrigDataType: ui32
T_212: (in (byte) (isObjectInFront() ^ 0x00000001) : byte)
  Class: Eq_212
  DataType: byte
  OrigDataType: byte
T_213: (in (uint32) (byte) (isObjectInFront() ^ 0x00000001) : uint32)
  Class: Eq_213
  DataType: uint32
  OrigDataType: uint32
T_214: (in 0x00000000 : word32)
  Class: Eq_213
  DataType: uint32
  OrigDataType: word32
T_215: (in (uint32) (byte) (isObjectInFront() ^ 0x00000001) != 0x00000000 : bool)
  Class: Eq_215
  DataType: bool
  OrigDataType: bool
T_216: (in fn000106D0 : ptr32)
  Class: Eq_161
  DataType: (ptr32 Eq_161)
  OrigDataType: (ptr32 (fn T_217 ()))
T_217: (in fn000106D0() : void)
  Class: Eq_163
  DataType: void
  OrigDataType: void
T_218: (in 0x0000006C : word32)
  Class: Eq_164
  DataType: ptr32
  OrigDataType: word32
T_219: (in fp == 0x0000006C : bool)
  Class: Eq_219
  DataType: bool
  OrigDataType: bool
T_220: (in fn000106D0 : ptr32)
  Class: Eq_161
  DataType: (ptr32 Eq_161)
  OrigDataType: (ptr32 (fn T_221 ()))
T_221: (in fn000106D0() : void)
  Class: Eq_163
  DataType: void
  OrigDataType: void
T_222: (in 0x00000070 : word32)
  Class: Eq_164
  DataType: ptr32
  OrigDataType: word32
T_223: (in fp == 0x00000070 : bool)
  Class: Eq_223
  DataType: bool
  OrigDataType: bool
T_224: (in fn00010688 : ptr32)
  Class: Eq_171
  DataType: (ptr32 Eq_171)
  OrigDataType: (ptr32 (fn T_225 ()))
T_225: (in fn00010688() : void)
  Class: Eq_173
  DataType: void
  OrigDataType: void
T_226: (in fn00010754 : ptr32)
  Class: Eq_188
  DataType: (ptr32 Eq_188)
  OrigDataType: (ptr32 (fn T_227 ()))
T_227: (in fn00010754() : void)
  Class: Eq_190
  DataType: void
  OrigDataType: void
T_228: (in fn00010754 : ptr32)
  Class: Eq_188
  DataType: (ptr32 Eq_188)
  OrigDataType: (ptr32 (fn T_229 ()))
T_229: (in fn00010754() : void)
  Class: Eq_190
  DataType: void
  OrigDataType: void
T_230: (in readDistance : ptr32)
  Class: Eq_204
  DataType: (ptr32 Eq_204)
  OrigDataType: (ptr32 (fn T_231 ()))
T_231: (in readDistance() : void)
  Class: Eq_206
  DataType: void
  OrigDataType: void
T_232: (in fn00010688 : ptr32)
  Class: Eq_171
  DataType: (ptr32 Eq_171)
  OrigDataType: (ptr32 (fn T_233 ()))
T_233: (in fn00010688() : void)
  Class: Eq_173
  DataType: void
  OrigDataType: void
T_234: (in fpscr : word32)
  Class: Eq_157
  DataType: word32
  OrigDataType: word32
T_235: (in fn000106AC : ptr32)
  Class: Eq_235
  DataType: (ptr32 Eq_235)
  OrigDataType: (ptr32 (fn T_237 ()))
T_236: (in signature of fn000106AC : void)
  Class: Eq_235
  DataType: (ptr32 Eq_235)
  OrigDataType: 
T_237: (in fn000106AC() : void)
  Class: Eq_237
  DataType: void
  OrigDataType: void
T_238: (in setUp : ptr32)
  Class: Eq_138
  DataType: (ptr32 Eq_138)
  OrigDataType: (ptr32 (fn T_240 (T_239)))
T_239: (in 0x00000002 : word32)
  Class: Eq_140
  DataType: word32
  OrigDataType: word32
T_240: (in setUp(0x00000002) : void)
  Class: Eq_142
  DataType: void
  OrigDataType: void
T_241: (in moveforward : ptr32)
  Class: Eq_241
  DataType: (ptr32 Eq_241)
  OrigDataType: (ptr32 (fn T_243 (T_234)))
T_242: (in signature of moveforward : void)
  Class: Eq_241
  DataType: (ptr32 Eq_241)
  OrigDataType: 
T_243: (in moveforward(fpscr) : void)
  Class: Eq_243
  DataType: void
  OrigDataType: void
T_244: (in fn00010730 : ptr32)
  Class: Eq_244
  DataType: (ptr32 Eq_244)
  OrigDataType: (ptr32 (fn T_246 ()))
T_245: (in signature of fn00010730 : void)
  Class: Eq_244
  DataType: (ptr32 Eq_244)
  OrigDataType: 
T_246: (in fn00010730() : void)
  Class: Eq_246
  DataType: void
  OrigDataType: void
T_247: (in 0x00000001 : word32)
  Class: Eq_140
  DataType: word32
  OrigDataType: word32
T_248: (in r0 != 0x00000001 : bool)
  Class: Eq_248
  DataType: bool
  OrigDataType: bool
T_249: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_251 ()))
T_250: (in signature of fn00010724 : void)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: 
T_251: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_252: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_253 ()))
T_253: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_254: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_255 ()))
T_255: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_256: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_257 ()))
T_257: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_258: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_259 ()))
T_259: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_260: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_261 ()))
T_261: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_262: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_263 ()))
T_263: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_264: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_265 ()))
T_265: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_266: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_267 ()))
T_267: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_268: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_269 ()))
T_269: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_270: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_271 ()))
T_271: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_272: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_273 ()))
T_273: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_274: (in fn00010760 : ptr32)
  Class: Eq_274
  DataType: (ptr32 Eq_274)
  OrigDataType: (ptr32 (fn T_276 ()))
T_275: (in signature of fn00010760 : void)
  Class: Eq_274
  DataType: (ptr32 Eq_274)
  OrigDataType: 
T_276: (in fn00010760() : void)
  Class: Eq_276
  DataType: void
  OrigDataType: void
T_277: (in 0x00000000 : word32)
  Class: Eq_277
  DataType: word32
  OrigDataType: word32
T_278: (in 0x00000000 : word32)
  Class: Eq_277
  DataType: word32
  OrigDataType: word32
T_279: (in 0x00000000 == 0x00000000 : bool)
  Class: Eq_279
  DataType: bool
  OrigDataType: bool
T_280: (in fn000106C4 : ptr32)
  Class: Eq_280
  DataType: (ptr32 Eq_280)
  OrigDataType: (ptr32 (fn T_282 ()))
T_281: (in signature of fn000106C4 : void)
  Class: Eq_280
  DataType: (ptr32 Eq_280)
  OrigDataType: 
T_282: (in fn000106C4() : void)
  Class: Eq_282
  DataType: void
  OrigDataType: void
T_283: (in fn00010718 : ptr32)
  Class: Eq_135
  DataType: (ptr32 Eq_135)
  OrigDataType: (ptr32 (fn T_284 ()))
T_284: (in fn00010718() : void)
  Class: Eq_137
  DataType: void
  OrigDataType: void
T_285: (in fn00010760 : ptr32)
  Class: Eq_274
  DataType: (ptr32 Eq_274)
  OrigDataType: (ptr32 (fn T_286 ()))
T_286: (in fn00010760() : void)
  Class: Eq_276
  DataType: void
  OrigDataType: void
T_287: (in 0x00000006 : word32)
  Class: Eq_287
  DataType: word32
  OrigDataType: word32
T_288: (in 0x00000000 : word32)
  Class: Eq_287
  DataType: word32
  OrigDataType: word32
T_289: (in 0x00000006 == 0x00000000 : bool)
  Class: Eq_289
  DataType: bool
  OrigDataType: bool
T_290: (in fn000106C4 : ptr32)
  Class: Eq_280
  DataType: (ptr32 Eq_280)
  OrigDataType: (ptr32 (fn T_291 ()))
T_291: (in fn000106C4() : void)
  Class: Eq_282
  DataType: void
  OrigDataType: void
T_292: (in fn00010760 : ptr32)
  Class: Eq_274
  DataType: (ptr32 Eq_274)
  OrigDataType: (ptr32 (fn T_293 ()))
T_293: (in fn00010760() : void)
  Class: Eq_276
  DataType: void
  OrigDataType: void
T_294: (in 0x0000000C : word32)
  Class: Eq_294
  DataType: word32
  OrigDataType: word32
T_295: (in 0x00000000 : word32)
  Class: Eq_294
  DataType: word32
  OrigDataType: word32
T_296: (in 0x0000000C == 0x00000000 : bool)
  Class: Eq_296
  DataType: bool
  OrigDataType: bool
T_297: (in fn000106C4 : ptr32)
  Class: Eq_280
  DataType: (ptr32 Eq_280)
  OrigDataType: (ptr32 (fn T_298 ()))
T_298: (in fn000106C4() : void)
  Class: Eq_282
  DataType: void
  OrigDataType: void
T_299: (in fn00010760 : ptr32)
  Class: Eq_274
  DataType: (ptr32 Eq_274)
  OrigDataType: (ptr32 (fn T_300 ()))
T_300: (in fn00010760() : void)
  Class: Eq_276
  DataType: void
  OrigDataType: void
T_301: (in r0_112 : word32)
  Class: Eq_140
  DataType: word32
  OrigDataType: word32
T_302: (in 0x0000001A : word32)
  Class: Eq_140
  DataType: word32
  OrigDataType: word32
T_303: (in 0x0000001A : word32)
  Class: Eq_303
  DataType: word32
  OrigDataType: word32
T_304: (in 0x00000000 : word32)
  Class: Eq_303
  DataType: word32
  OrigDataType: word32
T_305: (in 0x0000001A == 0x00000000 : bool)
  Class: Eq_305
  DataType: bool
  OrigDataType: bool
T_306: (in fn000106C4 : ptr32)
  Class: Eq_280
  DataType: (ptr32 Eq_280)
  OrigDataType: (ptr32 (fn T_307 ()))
T_307: (in fn000106C4() : void)
  Class: Eq_282
  DataType: void
  OrigDataType: void
T_308: (in 00010D68 : ptr32)
  Class: Eq_308
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_309 t0000)))
T_309: (in Mem116[0x00010D68:word32] : word32)
  Class: Eq_140
  DataType: word32
  OrigDataType: word32
T_310: (in fn000106C4 : ptr32)
  Class: Eq_280
  DataType: (ptr32 Eq_280)
  OrigDataType: (ptr32 (fn T_311 ()))
T_311: (in fn000106C4() : void)
  Class: Eq_282
  DataType: void
  OrigDataType: void
T_312: (in r3 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_313: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_315 ()))
T_314: (in signature of fn000106B8 : void)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: 
T_315: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_316: (in fn0001073C : ptr32)
  Class: Eq_316
  DataType: (ptr32 Eq_316)
  OrigDataType: (ptr32 (fn T_318 ()))
T_317: (in signature of fn0001073C : void)
  Class: Eq_316
  DataType: (ptr32 Eq_316)
  OrigDataType: 
T_318: (in fn0001073C() : void)
  Class: Eq_318
  DataType: void
  OrigDataType: void
T_319: (in 0x00000000 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_320: (in r3 == 0x00000000 : bool)
  Class: Eq_320
  DataType: bool
  OrigDataType: bool
T_321: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_322 ()))
T_322: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_323: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_324 ()))
T_324: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_325: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_326 ()))
T_326: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_327: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_328 ()))
T_328: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_329: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_330 ()))
T_330: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_331: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_332 ()))
T_332: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_333: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_334 ()))
T_334: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_335: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_336 ()))
T_336: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_337: (in dwLoc0C_59 : int32)
  Class: Eq_337
  DataType: int32
  OrigDataType: int32
T_338: (in 0x00000014 : word32)
  Class: Eq_337
  DataType: int32
  OrigDataType: word32
T_339: (in 0x00000000 : word32)
  Class: Eq_337
  DataType: int32
  OrigDataType: int32
T_340: (in dwLoc0C_59 > 0x00000000 : bool)
  Class: Eq_340
  DataType: bool
  OrigDataType: bool
T_341: (in fn0001073C : ptr32)
  Class: Eq_316
  DataType: (ptr32 Eq_316)
  OrigDataType: (ptr32 (fn T_342 ()))
T_342: (in fn0001073C() : void)
  Class: Eq_318
  DataType: void
  OrigDataType: void
T_343: (in fn0001073C : ptr32)
  Class: Eq_316
  DataType: (ptr32 Eq_316)
  OrigDataType: (ptr32 (fn T_344 ()))
T_344: (in fn0001073C() : void)
  Class: Eq_318
  DataType: void
  OrigDataType: void
T_345: (in fn0001073C : ptr32)
  Class: Eq_316
  DataType: (ptr32 Eq_316)
  OrigDataType: (ptr32 (fn T_346 ()))
T_346: (in fn0001073C() : void)
  Class: Eq_318
  DataType: void
  OrigDataType: void
T_347: (in fn0001073C : ptr32)
  Class: Eq_316
  DataType: (ptr32 Eq_316)
  OrigDataType: (ptr32 (fn T_348 ()))
T_348: (in fn0001073C() : void)
  Class: Eq_318
  DataType: void
  OrigDataType: void
T_349: (in 0x0000000A : word32)
  Class: Eq_349
  DataType: int32
  OrigDataType: int32
T_350: (in dwLoc0C_59 - 0x0000000A : word32)
  Class: Eq_337
  DataType: int32
  OrigDataType: int32
T_351: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_352 ()))
T_352: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_353: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_354 ()))
T_354: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_355: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_356 ()))
T_356: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_357: (in r0 : (ptr32 word32))
  Class: Eq_357
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_361 t0000)))
T_358: (in r3_13 : word32)
  Class: Eq_358
  DataType: word32
  OrigDataType: word32
T_359: (in 0x00000000 : word32)
  Class: Eq_359
  DataType: word32
  OrigDataType: word32
T_360: (in r0 + 0x00000000 : word32)
  Class: Eq_360
  DataType: word32
  OrigDataType: word32
T_361: (in Mem11[r0 + 0x00000000:word32] : word32)
  Class: Eq_358
  DataType: word32
  OrigDataType: word32
T_362: (in 0x00000001 : word32)
  Class: Eq_358
  DataType: word32
  OrigDataType: word32
T_363: (in r3_13 != 0x00000001 : bool)
  Class: Eq_363
  DataType: bool
  OrigDataType: bool
T_364: (in 0x00000002 : word32)
  Class: Eq_358
  DataType: word32
  OrigDataType: word32
T_365: (in r3_13 != 0x00000002 : bool)
  Class: Eq_365
  DataType: bool
  OrigDataType: bool
T_366: (in motorMove : ptr32)
  Class: Eq_366
  DataType: (ptr32 Eq_366)
  OrigDataType: (ptr32 (fn T_369 (T_368)))
T_367: (in signature of motorMove : void)
  Class: Eq_366
  DataType: (ptr32 Eq_366)
  OrigDataType: 
T_368: (in 0x00000000 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_369: (in motorMove(0x00000000) : void)
  Class: Eq_369
  DataType: void
  OrigDataType: void
T_370: (in 0x00000003 : word32)
  Class: Eq_358
  DataType: word32
  OrigDataType: word32
T_371: (in r3_13 != 0x00000003 : bool)
  Class: Eq_371
  DataType: bool
  OrigDataType: bool
T_372: (in motorMove : ptr32)
  Class: Eq_366
  DataType: (ptr32 Eq_366)
  OrigDataType: (ptr32 (fn T_374 (T_373)))
T_373: (in 0x00000000 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_374: (in motorMove(0x00000000) : void)
  Class: Eq_369
  DataType: void
  OrigDataType: void
T_375: (in 0x00000004 : word32)
  Class: Eq_358
  DataType: word32
  OrigDataType: word32
T_376: (in r3_13 != 0x00000004 : bool)
  Class: Eq_376
  DataType: bool
  OrigDataType: bool
T_377: (in motorMove : ptr32)
  Class: Eq_366
  DataType: (ptr32 Eq_366)
  OrigDataType: (ptr32 (fn T_379 (T_378)))
T_378: (in 0x00000001 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_379: (in motorMove(0x00000001) : void)
  Class: Eq_369
  DataType: void
  OrigDataType: void
T_380: (in motorMove : ptr32)
  Class: Eq_366
  DataType: (ptr32 Eq_366)
  OrigDataType: (ptr32 (fn T_382 (T_381)))
T_381: (in 0x00000000 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_382: (in motorMove(0x00000000) : void)
  Class: Eq_369
  DataType: void
  OrigDataType: void
T_383: (in r0 : (ptr32 word32))
  Class: Eq_383
  DataType: (ptr32 word32)
  OrigDataType: (ptr32 (struct (0 T_387 t0000)))
T_384: (in r3_13 : word32)
  Class: Eq_384
  DataType: word32
  OrigDataType: word32
T_385: (in 0x00000000 : word32)
  Class: Eq_385
  DataType: word32
  OrigDataType: word32
T_386: (in r0 + 0x00000000 : word32)
  Class: Eq_386
  DataType: word32
  OrigDataType: word32
T_387: (in Mem11[r0 + 0x00000000:word32] : word32)
  Class: Eq_384
  DataType: word32
  OrigDataType: word32
T_388: (in 0x00000001 : word32)
  Class: Eq_384
  DataType: word32
  OrigDataType: word32
T_389: (in r3_13 != 0x00000001 : bool)
  Class: Eq_389
  DataType: bool
  OrigDataType: bool
T_390: (in 0x00000002 : word32)
  Class: Eq_384
  DataType: word32
  OrigDataType: word32
T_391: (in r3_13 != 0x00000002 : bool)
  Class: Eq_391
  DataType: bool
  OrigDataType: bool
T_392: (in motorMove : ptr32)
  Class: Eq_366
  DataType: (ptr32 Eq_366)
  OrigDataType: (ptr32 (fn T_394 (T_393)))
T_393: (in 0x00000001 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_394: (in motorMove(0x00000001) : void)
  Class: Eq_369
  DataType: void
  OrigDataType: void
T_395: (in 0x00000003 : word32)
  Class: Eq_384
  DataType: word32
  OrigDataType: word32
T_396: (in r3_13 != 0x00000003 : bool)
  Class: Eq_396
  DataType: bool
  OrigDataType: bool
T_397: (in motorMove : ptr32)
  Class: Eq_366
  DataType: (ptr32 Eq_366)
  OrigDataType: (ptr32 (fn T_399 (T_398)))
T_398: (in 0x00000001 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_399: (in motorMove(0x00000001) : void)
  Class: Eq_369
  DataType: void
  OrigDataType: void
T_400: (in 0x00000004 : word32)
  Class: Eq_384
  DataType: word32
  OrigDataType: word32
T_401: (in r3_13 != 0x00000004 : bool)
  Class: Eq_401
  DataType: bool
  OrigDataType: bool
T_402: (in motorMove : ptr32)
  Class: Eq_366
  DataType: (ptr32 Eq_366)
  OrigDataType: (ptr32 (fn T_404 (T_403)))
T_403: (in 0x00000000 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_404: (in motorMove(0x00000000) : void)
  Class: Eq_369
  DataType: void
  OrigDataType: void
T_405: (in motorMove : ptr32)
  Class: Eq_366
  DataType: (ptr32 Eq_366)
  OrigDataType: (ptr32 (fn T_407 (T_406)))
T_406: (in 0x00000001 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_407: (in motorMove(0x00000001) : void)
  Class: Eq_369
  DataType: void
  OrigDataType: void
T_408: (in motorMove : ptr32)
  Class: Eq_366
  DataType: (ptr32 Eq_366)
  OrigDataType: (ptr32 (fn T_410 (T_409)))
T_409: (in 0x00000000 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_410: (in motorMove(0x00000000) : void)
  Class: Eq_369
  DataType: void
  OrigDataType: void
T_411: (in motorMove : ptr32)
  Class: Eq_366
  DataType: (ptr32 Eq_366)
  OrigDataType: (ptr32 (fn T_413 (T_412)))
T_412: (in 0x00000000 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_413: (in motorMove(0x00000000) : void)
  Class: Eq_369
  DataType: void
  OrigDataType: void
T_414: (in motorMove : ptr32)
  Class: Eq_366
  DataType: (ptr32 Eq_366)
  OrigDataType: (ptr32 (fn T_416 (T_415)))
T_415: (in 0x00000001 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_416: (in motorMove(0x00000001) : void)
  Class: Eq_369
  DataType: void
  OrigDataType: void
T_417: (in motorMove : ptr32)
  Class: Eq_366
  DataType: (ptr32 Eq_366)
  OrigDataType: (ptr32 (fn T_419 (T_418)))
T_418: (in 0x00000000 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_419: (in motorMove(0x00000000) : void)
  Class: Eq_369
  DataType: void
  OrigDataType: void
T_420: (in fn000106DC : ptr32)
  Class: Eq_420
  DataType: (ptr32 Eq_420)
  OrigDataType: (ptr32 (fn T_422 ()))
T_421: (in signature of fn000106DC : void)
  Class: Eq_420
  DataType: (ptr32 Eq_420)
  OrigDataType: 
T_422: (in fn000106DC() : void)
  Class: Eq_422
  DataType: void
  OrigDataType: void
T_423: (in motorStop : ptr32)
  Class: Eq_423
  DataType: (ptr32 Eq_423)
  OrigDataType: (ptr32 (fn T_425 ()))
T_424: (in signature of motorStop : void)
  Class: Eq_423
  DataType: (ptr32 Eq_423)
  OrigDataType: 
T_425: (in motorStop() : void)
  Class: Eq_425
  DataType: void
  OrigDataType: void
T_426: (in motorStop : ptr32)
  Class: Eq_423
  DataType: (ptr32 Eq_423)
  OrigDataType: (ptr32 (fn T_427 ()))
T_427: (in motorStop() : void)
  Class: Eq_425
  DataType: void
  OrigDataType: void
T_428: (in motorStop : ptr32)
  Class: Eq_423
  DataType: (ptr32 Eq_423)
  OrigDataType: (ptr32 (fn T_429 ()))
T_429: (in motorStop() : void)
  Class: Eq_425
  DataType: void
  OrigDataType: void
T_430: (in motorStop : ptr32)
  Class: Eq_423
  DataType: (ptr32 Eq_423)
  OrigDataType: (ptr32 (fn T_431 ()))
T_431: (in motorStop() : void)
  Class: Eq_425
  DataType: void
  OrigDataType: void
T_432: (in fn000106DC : ptr32)
  Class: Eq_420
  DataType: (ptr32 Eq_420)
  OrigDataType: (ptr32 (fn T_433 ()))
T_433: (in fn000106DC() : void)
  Class: Eq_422
  DataType: void
  OrigDataType: void
T_434: (in motorMove : ptr32)
  Class: Eq_366
  DataType: (ptr32 Eq_366)
  OrigDataType: (ptr32 (fn T_436 (T_435)))
T_435: (in 0x00000001 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_436: (in motorMove(0x00000001) : void)
  Class: Eq_369
  DataType: void
  OrigDataType: void
T_437: (in motorMove : ptr32)
  Class: Eq_366
  DataType: (ptr32 Eq_366)
  OrigDataType: (ptr32 (fn T_439 (T_438)))
T_438: (in 0x00000001 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_439: (in motorMove(0x00000001) : void)
  Class: Eq_369
  DataType: void
  OrigDataType: void
T_440: (in motorMove : ptr32)
  Class: Eq_366
  DataType: (ptr32 Eq_366)
  OrigDataType: (ptr32 (fn T_442 (T_441)))
T_441: (in 0x00000000 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_442: (in motorMove(0x00000000) : void)
  Class: Eq_369
  DataType: void
  OrigDataType: void
T_443: (in motorMove : ptr32)
  Class: Eq_366
  DataType: (ptr32 Eq_366)
  OrigDataType: (ptr32 (fn T_445 (T_444)))
T_444: (in 0x00000001 : word32)
  Class: Eq_312
  DataType: word32
  OrigDataType: word32
T_445: (in motorMove(0x00000001) : void)
  Class: Eq_369
  DataType: void
  OrigDataType: void
T_446: (in motorStop : ptr32)
  Class: Eq_423
  DataType: (ptr32 Eq_423)
  OrigDataType: (ptr32 (fn T_447 ()))
T_447: (in motorStop() : void)
  Class: Eq_425
  DataType: void
  OrigDataType: void
T_448: (in motorStop : ptr32)
  Class: Eq_423
  DataType: (ptr32 Eq_423)
  OrigDataType: (ptr32 (fn T_449 ()))
T_449: (in motorStop() : void)
  Class: Eq_425
  DataType: void
  OrigDataType: void
T_450: (in motorStop : ptr32)
  Class: Eq_423
  DataType: (ptr32 Eq_423)
  OrigDataType: (ptr32 (fn T_451 ()))
T_451: (in motorStop() : void)
  Class: Eq_425
  DataType: void
  OrigDataType: void
T_452: (in motorStop : ptr32)
  Class: Eq_423
  DataType: (ptr32 Eq_423)
  OrigDataType: (ptr32 (fn T_453 ()))
T_453: (in motorStop() : void)
  Class: Eq_425
  DataType: void
  OrigDataType: void
T_454: (in fn00010730 : ptr32)
  Class: Eq_244
  DataType: (ptr32 Eq_244)
  OrigDataType: (ptr32 (fn T_455 ()))
T_455: (in fn00010730() : void)
  Class: Eq_246
  DataType: void
  OrigDataType: void
T_456: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_457 ()))
T_457: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_458: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_459 ()))
T_459: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_460: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_461 ()))
T_461: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_462: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_463 ()))
T_463: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_464: (in r0 : ui32)
  Class: Eq_464
  DataType: ui32
  OrigDataType: ui32
T_465: (in d0 : word64)
  Class: Eq_465
  DataType: word64
  OrigDataType: word64
T_466: (in 00011220 : ptr32)
  Class: Eq_466
  DataType: (ptr32 (ptr32 (arr word64)))
  OrigDataType: (ptr32 (struct (0 T_467 t0000)))
T_467: (in Mem10[0x00011220:word32] : word32)
  Class: Eq_467
  DataType: (ptr32 (arr word64))
  OrigDataType: (ptr32 (struct (0 (arr T_715) a0000)))
T_468: (in 0x00000008 : ui32)
  Class: Eq_468
  DataType: ui32
  OrigDataType: ui32
T_469: (in r0 * 0x00000008 : word32)
  Class: Eq_469
  DataType: ui32
  OrigDataType: ui32
T_470: (in Mem10[0x00011220:word32][r0 * 0x00000008] : word64)
  Class: Eq_465
  DataType: word64
  OrigDataType: word64
T_471: (in r0 : ui32)
  Class: Eq_471
  DataType: ui32
  OrigDataType: ui32
T_472: (in fn000106A0 : ptr32)
  Class: Eq_472
  DataType: (ptr32 Eq_472)
  OrigDataType: (ptr32 (fn T_474 ()))
T_473: (in signature of fn000106A0 : void)
  Class: Eq_472
  DataType: (ptr32 Eq_472)
  OrigDataType: 
T_474: (in fn000106A0() : void)
  Class: Eq_474
  DataType: void
  OrigDataType: void
T_475: (in r3_r2_19 : word64)
  Class: Eq_475
  DataType: word64
  OrigDataType: word64
T_476: (in 00011274 : ptr32)
  Class: Eq_476
  DataType: (ptr32 (ptr32 (arr word64)))
  OrigDataType: (ptr32 (struct (0 T_477 t0000)))
T_477: (in Mem11[0x00011274:word32] : word32)
  Class: Eq_477
  DataType: (ptr32 (arr word64))
  OrigDataType: (ptr32 (struct (0 (arr T_716) a0000)))
T_478: (in 0x00000008 : ui32)
  Class: Eq_478
  DataType: ui32
  OrigDataType: ui32
T_479: (in r0 * 0x00000008 : word32)
  Class: Eq_479
  DataType: ui32
  OrigDataType: ui32
T_480: (in Mem11[0x00011274:word32][r0 * 0x00000008] : word64)
  Class: Eq_475
  DataType: word64
  OrigDataType: word64
T_481: (in fn0001067C : ptr32)
  Class: Eq_481
  DataType: (ptr32 Eq_481)
  OrigDataType: (ptr32 (fn T_483 ()))
T_482: (in signature of fn0001067C : void)
  Class: Eq_481
  DataType: (ptr32 Eq_481)
  OrigDataType: 
T_483: (in fn0001067C() : void)
  Class: Eq_483
  DataType: void
  OrigDataType: void
T_484: (in __vmov_f64 : ptr32)
  Class: Eq_484
  DataType: (ptr32 Eq_484)
  OrigDataType: (ptr32 (fn T_489 (T_488)))
T_485: (in signature of __vmov_f64 : void)
  Class: Eq_484
  DataType: (ptr32 Eq_484)
  OrigDataType: 
T_486: (in  : word64)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: 
T_487: (in SLICE(r3_r2_19, word32, 0) : word32)
  Class: Eq_487
  DataType: word32
  OrigDataType: word32
T_488: (in (word64) SLICE(r3_r2_19, word32, 0) : word64)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: word64
T_489: (in __vmov_f64((word64) (word32) r3_r2_19) : word64)
  Class: Eq_489
  DataType: (ptr64 Eq_489)
  OrigDataType: (ptr64 (fn T_490 ()))
T_490: (in __vmov_f64((word64) (word32) r3_r2_19)() : word32)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: word32
T_491: (in r0 : word32)
  Class: Eq_491
  DataType: word32
  OrigDataType: word32
T_492: (in d0 : Eq_486)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: word64
T_493: (in __vmov_f64 : ptr32)
  Class: Eq_484
  DataType: (ptr32 Eq_484)
  OrigDataType: (ptr32 (fn T_510 (T_509)))
T_494: (in __vmov_f64 : ptr32)
  Class: Eq_484
  DataType: (ptr32 Eq_484)
  OrigDataType: (ptr32 (fn T_508 (T_507)))
T_495: (in __vmul_f64 : ptr32)
  Class: Eq_495
  DataType: (ptr32 Eq_495)
  OrigDataType: (ptr32 (fn T_502 (T_499, T_501)))
T_496: (in signature of __vmul_f64 : void)
  Class: Eq_495
  DataType: (ptr32 Eq_495)
  OrigDataType: 
T_497: (in  : word64)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: 
T_498: (in  : word64)
  Class: Eq_498
  DataType: Eq_498
  OrigDataType: 
T_499: (in (real64) r0 : real64)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: real64
T_500: (in 000112C8 : ptr32)
  Class: Eq_500
  DataType: (ptr32 Eq_498)
  OrigDataType: (ptr32 (struct (0 T_501 t0000)))
T_501: (in Mem10[0x000112C8:word32] : word32)
  Class: Eq_498
  DataType: Eq_498
  OrigDataType: (union (word64 u1) (word32 u0))
T_502: (in __vmul_f64((real64) r0, globals->t112C8) : (arr word64 1))
  Class: Eq_502
  DataType: (arr real64 1)
  OrigDataType: (arr real64 1)
T_503: (in __vmul_f64 : ptr32)
  Class: Eq_495
  DataType: (ptr32 Eq_495)
  OrigDataType: (ptr32 (fn T_506 (T_492, T_505)))
T_504: (in 000112D0 : ptr32)
  Class: Eq_504
  DataType: (ptr32 Eq_498)
  OrigDataType: (ptr32 (struct (0 T_505 t0000)))
T_505: (in Mem10[0x000112D0:word32] : word32)
  Class: Eq_498
  DataType: Eq_498
  OrigDataType: (union (word64 u1) (word32 u0))
T_506: (in __vmul_f64(d0, globals->t112D0) : (arr word64 1))
  Class: Eq_502
  DataType: (arr real64 1)
  OrigDataType: (arr real64 1)
T_507: (in __vmul_f64((real64) r0, globals->t112C8) / __vmul_f64(d0, globals->t112D0) : real64)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: real64
T_508: (in __vmov_f64(__vmul_f64((real64) r0, globals->t112C8) / __vmul_f64(d0, globals->t112D0)) : word64)
  Class: Eq_489
  DataType: (ptr64 Eq_489)
  OrigDataType: (ptr64 (fn T_509 ()))
T_509: (in __vmov_f64(__vmul_f64((real64) r0, globals->t112C8) / __vmul_f64(d0, globals->t112D0))() : word32)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: (union (word64 u1) (word32 u0))
T_510: (in __vmov_f64(__vmov_f64(__vmul_f64((real64) r0, globals->t112C8) / __vmul_f64(d0, globals->t112D0))()) : word64)
  Class: Eq_489
  DataType: (ptr64 Eq_489)
  OrigDataType: (ptr64 (fn T_511 ()))
T_511: (in __vmov_f64(__vmov_f64(__vmul_f64((real64) r0, globals->t112C8) / __vmul_f64(d0, globals->t112D0))())() : word32)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: word32
T_512: (in fn00010748 : ptr32)
  Class: Eq_512
  DataType: (ptr32 Eq_512)
  OrigDataType: (ptr32 (fn T_514 ()))
T_513: (in signature of fn00010748 : void)
  Class: Eq_512
  DataType: (ptr32 Eq_512)
  OrigDataType: 
T_514: (in fn00010748() : void)
  Class: Eq_514
  DataType: void
  OrigDataType: void
T_515: (in readPulses : ptr32)
  Class: Eq_515
  DataType: (ptr32 Eq_515)
  OrigDataType: (ptr32 (fn T_517 ()))
T_516: (in signature of readPulses : void)
  Class: Eq_515
  DataType: (ptr32 Eq_515)
  OrigDataType: 
T_517: (in readPulses() : void)
  Class: Eq_517
  DataType: void
  OrigDataType: void
T_518: (in __vadd_f64 : ptr32)
  Class: Eq_518
  DataType: (ptr32 Eq_518)
  OrigDataType: (ptr32 (fn T_532 (T_526, T_531)))
T_519: (in signature of __vadd_f64 : void)
  Class: Eq_518
  DataType: (ptr32 Eq_518)
  OrigDataType: 
T_520: (in  : word64)
  Class: Eq_520
  DataType: word64
  OrigDataType: 
T_521: (in  : word64)
  Class: Eq_521
  DataType: word64
  OrigDataType: 
T_522: (in 00011550 : ptr32)
  Class: Eq_522
  DataType: (ptr32 (ptr32 Eq_523))
  OrigDataType: (ptr32 (struct (0 T_523 t0000)))
T_523: (in Mem13[0x00011550:word32] : word32)
  Class: Eq_523
  DataType: (ptr32 Eq_523)
  OrigDataType: (ptr32 (struct (0 T_526 t0000)))
T_524: (in 0x00000000 : word32)
  Class: Eq_524
  DataType: word32
  OrigDataType: word32
T_525: (in Mem13[0x00011550:word32] + 0x00000000 : word32)
  Class: Eq_525
  DataType: word32
  OrigDataType: word32
T_526: (in Mem13[Mem13[0x00011550:word32] + 0x00000000:word64] : word64)
  Class: Eq_520
  DataType: word64
  OrigDataType: word64
T_527: (in 00011550 : ptr32)
  Class: Eq_527
  DataType: (ptr32 (ptr32 Eq_523))
  OrigDataType: (ptr32 (struct (0 T_528 t0000)))
T_528: (in Mem13[0x00011550:word32] : word32)
  Class: Eq_523
  DataType: (ptr32 Eq_523)
  OrigDataType: (ptr32 (struct (10 word64 qw0010)))
T_529: (in 16 : int32)
  Class: Eq_529
  DataType: int32
  OrigDataType: int32
T_530: (in Mem13[0x00011550:word32] + 16 : word32)
  Class: Eq_530
  DataType: word32
  OrigDataType: word32
T_531: (in Mem13[Mem13[0x00011550:word32] + 16:word64] : word64)
  Class: Eq_521
  DataType: word64
  OrigDataType: word64
T_532: (in __vadd_f64(globals->ptr11550->qw0000, globals->ptr11550->qw0010) : (arr word64 1))
  Class: Eq_532
  DataType: (arr word64 1)
  OrigDataType: (arr word64 1)
T_533: (in fn00010688 : ptr32)
  Class: Eq_171
  DataType: (ptr32 Eq_171)
  OrigDataType: (ptr32 (fn T_534 ()))
T_534: (in fn00010688() : void)
  Class: Eq_173
  DataType: void
  OrigDataType: void
T_535: (in fn00010694 : ptr32)
  Class: Eq_535
  DataType: (ptr32 Eq_535)
  OrigDataType: (ptr32 (fn T_537 ()))
T_536: (in signature of fn00010694 : void)
  Class: Eq_535
  DataType: (ptr32 Eq_535)
  OrigDataType: 
T_537: (in fn00010694() : void)
  Class: Eq_537
  DataType: void
  OrigDataType: void
T_538: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_539 ()))
T_539: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_540: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_541 ()))
T_541: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_542: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_543 ()))
T_543: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_544: (in fn00010730 : ptr32)
  Class: Eq_244
  DataType: (ptr32 Eq_244)
  OrigDataType: (ptr32 (fn T_545 ()))
T_545: (in fn00010730() : void)
  Class: Eq_246
  DataType: void
  OrigDataType: void
T_546: (in 0x00000001 : word32)
  Class: Eq_145
  DataType: word32
  OrigDataType: word32
T_547: (in r0 != 0x00000001 : bool)
  Class: Eq_547
  DataType: bool
  OrigDataType: bool
T_548: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_549 ()))
T_549: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_550: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_551 ()))
T_551: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_552: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_553 ()))
T_553: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_554: (in fn000106E8 : ptr32)
  Class: Eq_158
  DataType: (ptr32 Eq_158)
  OrigDataType: (ptr32 (fn T_555 ()))
T_555: (in fn000106E8() : void)
  Class: Eq_160
  DataType: void
  OrigDataType: void
T_556: (in fn00010718 : ptr32)
  Class: Eq_135
  DataType: (ptr32 Eq_135)
  OrigDataType: (ptr32 (fn T_557 ()))
T_557: (in fn00010718() : void)
  Class: Eq_137
  DataType: void
  OrigDataType: void
T_558: (in r0 : word32)
  Class: Eq_558
  DataType: word32
  OrigDataType: word32
T_559: (in fn00010694 : ptr32)
  Class: Eq_535
  DataType: (ptr32 Eq_535)
  OrigDataType: (ptr32 (fn T_560 ()))
T_560: (in fn00010694() : void)
  Class: Eq_537
  DataType: void
  OrigDataType: void
T_561: (in 0x00000001 : word32)
  Class: Eq_558
  DataType: word32
  OrigDataType: word32
T_562: (in r0 != 0x00000001 : bool)
  Class: Eq_562
  DataType: bool
  OrigDataType: bool
T_563: (in r0 == 0x00000001 : bool)
  Class: Eq_563
  DataType: bool
  OrigDataType: bool
T_564: (in r0 : uint32)
  Class: Eq_564
  DataType: uint32
  OrigDataType: word32
T_565: (in r3_21 : ui32)
  Class: Eq_565
  DataType: ui32
  OrigDataType: ui32
T_566: (in fn00010694 : ptr32)
  Class: Eq_535
  DataType: (ptr32 Eq_535)
  OrigDataType: (ptr32 (fn T_567 ()))
T_567: (in fn00010694() : void)
  Class: Eq_537
  DataType: void
  OrigDataType: void
T_568: (in true : bool)
  Class: Eq_568
  DataType: bool
  OrigDataType: bool
T_569: (in 0x00000001 : word32)
  Class: Eq_565
  DataType: ui32
  OrigDataType: word32
T_570: (in fn00010694 : ptr32)
  Class: Eq_535
  DataType: (ptr32 Eq_535)
  OrigDataType: (ptr32 (fn T_571 ()))
T_571: (in fn00010694() : void)
  Class: Eq_537
  DataType: void
  OrigDataType: void
T_572: (in 0x00000007 : word32)
  Class: Eq_572
  DataType: word32
  OrigDataType: word32
T_573: (in 0x00000000 : word32)
  Class: Eq_572
  DataType: word32
  OrigDataType: word32
T_574: (in 0x00000007 == 0x00000000 : bool)
  Class: Eq_574
  DataType: bool
  OrigDataType: bool
T_575: (in 0x00000000 : word32)
  Class: Eq_565
  DataType: ui32
  OrigDataType: word32
T_576: (in 0x00000001 : word32)
  Class: Eq_576
  DataType: ui32
  OrigDataType: ui32
T_577: (in r3_21 & 0x00000001 : word32)
  Class: Eq_577
  DataType: ui32
  OrigDataType: ui32
T_578: (in (byte) (r3_21 & 0x00000001) : byte)
  Class: Eq_578
  DataType: byte
  OrigDataType: byte
T_579: (in (uint32) (byte) (r3_21 & 0x00000001) : uint32)
  Class: Eq_564
  DataType: uint32
  OrigDataType: uint32
T_580: (in fn00010730 : ptr32)
  Class: Eq_244
  DataType: (ptr32 Eq_244)
  OrigDataType: (ptr32 (fn T_581 ()))
T_581: (in fn00010730() : void)
  Class: Eq_246
  DataType: void
  OrigDataType: void
T_582: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_583 ()))
T_583: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_584: (in fn00010724 : ptr32)
  Class: Eq_249
  DataType: (ptr32 Eq_249)
  OrigDataType: (ptr32 (fn T_585 ()))
T_585: (in fn00010724() : void)
  Class: Eq_251
  DataType: void
  OrigDataType: void
T_586: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_587 ()))
T_587: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_588: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_589 ()))
T_589: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_590: (in d0 : Eq_486)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: word64
T_591: (in __vmul_f64 : ptr32)
  Class: Eq_495
  DataType: (ptr32 Eq_495)
  OrigDataType: (ptr32 (fn T_594 (T_590, T_593)))
T_592: (in 00011720 : ptr32)
  Class: Eq_592
  DataType: (ptr32 Eq_498)
  OrigDataType: (ptr32 (struct (0 T_593 t0000)))
T_593: (in Mem9[0x00011720:word32] : word32)
  Class: Eq_498
  DataType: Eq_498
  OrigDataType: (union (word64 u1) (word32 u0))
T_594: (in __vmul_f64(d0, globals->t11720) : (arr word64 1))
  Class: Eq_502
  DataType: (arr real64 1)
  OrigDataType: (arr word64 1)
T_595: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_596 ()))
T_596: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_597: (in fn000106DC : ptr32)
  Class: Eq_420
  DataType: (ptr32 Eq_420)
  OrigDataType: (ptr32 (fn T_598 ()))
T_598: (in fn000106DC() : void)
  Class: Eq_422
  DataType: void
  OrigDataType: void
T_599: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_600 ()))
T_600: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_601: (in q0 : Eq_486)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: word128
T_602: (in fn00010694 : ptr32)
  Class: Eq_535
  DataType: (ptr32 Eq_535)
  OrigDataType: (ptr32 (fn T_603 ()))
T_603: (in fn00010694() : void)
  Class: Eq_537
  DataType: void
  OrigDataType: void
T_604: (in 0x00000016 : word32)
  Class: Eq_604
  DataType: word32
  OrigDataType: word32
T_605: (in 0x00000000 : word32)
  Class: Eq_604
  DataType: word32
  OrigDataType: word32
T_606: (in 0x00000016 == 0x00000000 : bool)
  Class: Eq_606
  DataType: bool
  OrigDataType: bool
T_607: (in fn0001070C : ptr32)
  Class: Eq_607
  DataType: (ptr32 Eq_607)
  OrigDataType: (ptr32 (fn T_609 ()))
T_608: (in signature of fn0001070C : void)
  Class: Eq_607
  DataType: (ptr32 Eq_607)
  OrigDataType: 
T_609: (in fn0001070C() : void)
  Class: Eq_609
  DataType: void
  OrigDataType: void
T_610: (in fn00010694 : ptr32)
  Class: Eq_535
  DataType: (ptr32 Eq_535)
  OrigDataType: (ptr32 (fn T_611 ()))
T_611: (in fn00010694() : void)
  Class: Eq_537
  DataType: void
  OrigDataType: void
T_612: (in 0x00000015 : word32)
  Class: Eq_612
  DataType: word32
  OrigDataType: word32
T_613: (in 0x00000000 : word32)
  Class: Eq_612
  DataType: word32
  OrigDataType: word32
T_614: (in 0x00000015 == 0x00000000 : bool)
  Class: Eq_614
  DataType: bool
  OrigDataType: bool
T_615: (in fn0001070C : ptr32)
  Class: Eq_607
  DataType: (ptr32 Eq_607)
  OrigDataType: (ptr32 (fn T_616 ()))
T_616: (in fn0001070C() : void)
  Class: Eq_609
  DataType: void
  OrigDataType: void
T_617: (in d7_43 : real64)
  Class: Eq_617
  DataType: real64
  OrigDataType: real64
T_618: (in 0x00000000 : word32)
  Class: Eq_618
  DataType: word32
  OrigDataType: word32
T_619: (in (real64) 0x00000000 : real64)
  Class: Eq_619
  DataType: real64
  OrigDataType: real64
T_620: (in 000117F8 : ptr32)
  Class: Eq_620
  DataType: (ptr32 real32)
  OrigDataType: (ptr32 (struct (0 T_621 t0000)))
T_621: (in Mem36[0x000117F8:word32] : word32)
  Class: Eq_621
  DataType: real32
  OrigDataType: real32
T_622: (in (real64) 0x00000000 / globals->r117F8 : real64)
  Class: Eq_617
  DataType: real64
  OrigDataType: real64
T_623: (in fn00010688 : ptr32)
  Class: Eq_171
  DataType: (ptr32 Eq_171)
  OrigDataType: (ptr32 (fn T_624 ()))
T_624: (in fn00010688() : void)
  Class: Eq_173
  DataType: void
  OrigDataType: void
T_625: (in __vmov_f64 : ptr32)
  Class: Eq_484
  DataType: (ptr32 Eq_484)
  OrigDataType: (ptr32 (fn T_628 (T_627)))
T_626: (in SLICE(d7_43, word32, 0) : word32)
  Class: Eq_626
  DataType: word32
  OrigDataType: word32
T_627: (in (word64) SLICE(d7_43, word32, 0) : word64)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: word64
T_628: (in __vmov_f64((word64) (word32) d7_43) : word64)
  Class: Eq_489
  DataType: (ptr64 Eq_489)
  OrigDataType: (ptr64 (fn T_629 ()))
T_629: (in __vmov_f64((word64) (word32) d7_43)() : word32)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: word32
T_630: (in fn000106E8 : ptr32)
  Class: Eq_158
  DataType: (ptr32 Eq_158)
  OrigDataType: (ptr32 (fn T_631 ()))
T_631: (in fn000106E8() : void)
  Class: Eq_160
  DataType: void
  OrigDataType: void
T_632: (in prepareTrigger : ptr32)
  Class: Eq_632
  DataType: (ptr32 Eq_632)
  OrigDataType: (ptr32 (fn T_634 ()))
T_633: (in signature of prepareTrigger : void)
  Class: Eq_632
  DataType: (ptr32 Eq_632)
  OrigDataType: 
T_634: (in prepareTrigger() : void)
  Class: Eq_634
  DataType: void
  OrigDataType: void
T_635: (in calculateDistance : ptr32)
  Class: Eq_635
  DataType: (ptr32 Eq_635)
  OrigDataType: (ptr32 (fn T_647 (T_646)))
T_636: (in signature of calculateDistance : void)
  Class: Eq_635
  DataType: (ptr32 Eq_635)
  OrigDataType: 
T_637: (in __vmov_f64 : ptr32)
  Class: Eq_484
  DataType: (ptr32 Eq_484)
  OrigDataType: (ptr32 (fn T_645 (T_644)))
T_638: (in __vmov_f64 : ptr32)
  Class: Eq_484
  DataType: (ptr32 Eq_484)
  OrigDataType: (ptr32 (fn T_643 (T_642)))
T_639: (in getTime : ptr32)
  Class: Eq_639
  DataType: (ptr32 Eq_639)
  OrigDataType: (ptr32 (fn T_641 ()))
T_640: (in signature of getTime : void)
  Class: Eq_639
  DataType: (ptr32 Eq_639)
  OrigDataType: 
T_641: (in getTime() : word128)
  Class: Eq_641
  DataType: word128
  OrigDataType: word128
T_642: (in SLICE(getTime(), word64, 0) : word64)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: word64
T_643: (in __vmov_f64((word64) getTime()) : word64)
  Class: Eq_489
  DataType: (ptr64 Eq_489)
  OrigDataType: (ptr64 (fn T_644 ()))
T_644: (in __vmov_f64((word64) getTime())() : word32)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: (union (word64 u1) (word32 u0))
T_645: (in __vmov_f64(__vmov_f64((word64) getTime())()) : word64)
  Class: Eq_489
  DataType: (ptr64 Eq_489)
  OrigDataType: (ptr64 (fn T_646 ()))
T_646: (in __vmov_f64(__vmov_f64((word64) getTime())())() : word32)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: (union (word64 u1) (word32 u0))
T_647: (in calculateDistance(__vmov_f64(__vmov_f64((word64) getTime())())()) : void)
  Class: Eq_647
  DataType: void
  OrigDataType: void
T_648: (in prepareTrigger : ptr32)
  Class: Eq_632
  DataType: (ptr32 Eq_632)
  OrigDataType: (ptr32 (fn T_649 ()))
T_649: (in prepareTrigger() : void)
  Class: Eq_634
  DataType: void
  OrigDataType: void
T_650: (in calculateDistance : ptr32)
  Class: Eq_635
  DataType: (ptr32 Eq_635)
  OrigDataType: (ptr32 (fn T_660 (T_659)))
T_651: (in __vmov_f64 : ptr32)
  Class: Eq_484
  DataType: (ptr32 Eq_484)
  OrigDataType: (ptr32 (fn T_658 (T_657)))
T_652: (in __vmov_f64 : ptr32)
  Class: Eq_484
  DataType: (ptr32 Eq_484)
  OrigDataType: (ptr32 (fn T_656 (T_655)))
T_653: (in getTime : ptr32)
  Class: Eq_639
  DataType: (ptr32 Eq_639)
  OrigDataType: (ptr32 (fn T_654 ()))
T_654: (in getTime() : word128)
  Class: Eq_641
  DataType: word128
  OrigDataType: word128
T_655: (in SLICE(getTime(), word64, 0) : word64)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: word64
T_656: (in __vmov_f64((word64) getTime()) : word64)
  Class: Eq_489
  DataType: (ptr64 Eq_489)
  OrigDataType: (ptr64 (fn T_657 ()))
T_657: (in __vmov_f64((word64) getTime())() : word32)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: (union (word64 u1) (word32 u0))
T_658: (in __vmov_f64(__vmov_f64((word64) getTime())()) : word64)
  Class: Eq_489
  DataType: (ptr64 Eq_489)
  OrigDataType: (ptr64 (fn T_659 ()))
T_659: (in __vmov_f64(__vmov_f64((word64) getTime())())() : word32)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: (union (word64 u1) (word32 u0))
T_660: (in calculateDistance(__vmov_f64(__vmov_f64((word64) getTime())())()) : void)
  Class: Eq_647
  DataType: void
  OrigDataType: void
T_661: (in prepareTrigger : ptr32)
  Class: Eq_632
  DataType: (ptr32 Eq_632)
  OrigDataType: (ptr32 (fn T_662 ()))
T_662: (in prepareTrigger() : void)
  Class: Eq_634
  DataType: void
  OrigDataType: void
T_663: (in calculateDistance : ptr32)
  Class: Eq_635
  DataType: (ptr32 Eq_635)
  OrigDataType: (ptr32 (fn T_673 (T_672)))
T_664: (in __vmov_f64 : ptr32)
  Class: Eq_484
  DataType: (ptr32 Eq_484)
  OrigDataType: (ptr32 (fn T_671 (T_670)))
T_665: (in __vmov_f64 : ptr32)
  Class: Eq_484
  DataType: (ptr32 Eq_484)
  OrigDataType: (ptr32 (fn T_669 (T_668)))
T_666: (in getTime : ptr32)
  Class: Eq_639
  DataType: (ptr32 Eq_639)
  OrigDataType: (ptr32 (fn T_667 ()))
T_667: (in getTime() : word128)
  Class: Eq_641
  DataType: word128
  OrigDataType: word128
T_668: (in SLICE(getTime(), word64, 0) : word64)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: word64
T_669: (in __vmov_f64((word64) getTime()) : word64)
  Class: Eq_489
  DataType: (ptr64 Eq_489)
  OrigDataType: (ptr64 (fn T_670 ()))
T_670: (in __vmov_f64((word64) getTime())() : word32)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: (union (word64 u1) (word32 u0))
T_671: (in __vmov_f64(__vmov_f64((word64) getTime())()) : word64)
  Class: Eq_489
  DataType: (ptr64 Eq_489)
  OrigDataType: (ptr64 (fn T_672 ()))
T_672: (in __vmov_f64(__vmov_f64((word64) getTime())())() : word32)
  Class: Eq_486
  DataType: Eq_486
  OrigDataType: (union (word64 u1) (word32 u0))
T_673: (in calculateDistance(__vmov_f64(__vmov_f64((word64) getTime())())()) : void)
  Class: Eq_647
  DataType: void
  OrigDataType: void
T_674: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_675 ()))
T_675: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_676: (in fn000106B8 : ptr32)
  Class: Eq_313
  DataType: (ptr32 Eq_313)
  OrigDataType: (ptr32 (fn T_677 ()))
T_677: (in fn000106B8() : void)
  Class: Eq_315
  DataType: void
  OrigDataType: void
T_678: (in r0 : word32)
  Class: Eq_678
  DataType: word32
  OrigDataType: word32
T_679: (in r1 : word32)
  Class: Eq_679
  DataType: word32
  OrigDataType: word32
T_680: (in r2 : word32)
  Class: Eq_680
  DataType: word32
  OrigDataType: word32
T_681: (in r10 : word32)
  Class: Eq_681
  DataType: word32
  OrigDataType: word32
T_682: (in lr : (ptr32 code))
  Class: Eq_2
  DataType: (ptr32 code)
  OrigDataType: word32
T_683: (in r5_25 : (ptr32 (ptr32 (ptr32 (ptr32 (ptr32 code))))))
  Class: Eq_683
  DataType: (ptr32 (ptr32 (ptr32 (ptr32 (ptr32 code)))))
  OrigDataType: (union ((ptr32 (ptr32 (ptr32 (ptr32 (ptr32 code))))) u1) (ptr32 u0))
T_684: (in 000118F8 : ptr32)
  Class: Eq_684
  DataType: ptr32
  OrigDataType: ptr32
T_685: (in 00011938 : ptr32)
  Class: Eq_685
  DataType: (ptr32 int32)
  OrigDataType: (ptr32 (struct (0 T_686 t0000)))
T_686: (in Mem18[0x00011938:word32] : word32)
  Class: Eq_686
  DataType: int32
  OrigDataType: int32
T_687: (in 0x000118F8 + globals->dw11938 : word32)
  Class: Eq_683
  DataType: (ptr32 (ptr32 (ptr32 (ptr32 (ptr32 code)))))
  OrigDataType: ptr32
T_688: (in r6_26 : word32)
  Class: Eq_688
  DataType: int32
  OrigDataType: int32
T_689: (in 000118F4 : ptr32)
  Class: Eq_689
  DataType: (ptr32 (ptr32 (ptr32 (ptr32 (ptr32 code)))))
  OrigDataType: (union ((ptr32 (ptr32 (ptr32 (ptr32 (ptr32 code))))) u1) (ptr32 u0))
T_690: (in 00011934 : ptr32)
  Class: Eq_690
  DataType: (ptr32 (ptr32 (ptr32 (ptr32 (ptr32 (ptr32 code))))))
  OrigDataType: (ptr32 (struct (0 T_691 t0000)))
T_691: (in Mem18[0x00011934:word32] : word32)
  Class: Eq_691
  DataType: (ptr32 (ptr32 (ptr32 (ptr32 (ptr32 code)))))
  OrigDataType: (union ((ptr32 (ptr32 (ptr32 (ptr32 (ptr32 code))))) u1) (ptr32 u0))
T_692: (in 0x000118F4 + Mem18[0x00011934:word32] : word32)
  Class: Eq_692
  DataType: Eq_692
  OrigDataType: (union (int32 u1) (ptr32 u0))
T_693: (in 0x000118F4 + Mem18[0x00011934:word32] - r5_25 : word32)
  Class: Eq_688
  DataType: int32
  OrigDataType: int32
T_694: (in r7_21 : word32)
  Class: Eq_678
  DataType: word32
  OrigDataType: word32
T_695: (in r8_28 : word32)
  Class: Eq_679
  DataType: word32
  OrigDataType: word32
T_696: (in r9_30 : word32)
  Class: Eq_680
  DataType: word32
  OrigDataType: word32
T_697: (in lr_32 : word32)
  Class: Eq_697
  DataType: word32
  OrigDataType: word32
T_698: (in _init : ptr32)
  Class: Eq_698
  DataType: (ptr32 Eq_698)
  OrigDataType: (ptr32 (fn T_700 (T_682)))
T_699: (in signature of _init : void)
  Class: Eq_698
  DataType: (ptr32 Eq_698)
  OrigDataType: 
T_700: (in _init(lr) : word32)
  Class: Eq_697
  DataType: word32
  OrigDataType: word32
T_701: (in r6_38 : int32)
  Class: Eq_701
  DataType: int32
  OrigDataType: int32
T_702: (in 2 : int32)
  Class: Eq_702
  DataType: int32
  OrigDataType: int32
T_703: (in r6_26 >> 2 : word32)
  Class: Eq_701
  DataType: int32
  OrigDataType: int32
T_704: (in r6_26 >> 2 : word32)
  Class: Eq_704
  DataType: int32
  OrigDataType: int32
T_705: (in 0x00000000 : word32)
  Class: Eq_704
  DataType: int32
  OrigDataType: word32
T_706: (in r6_26 >> 2 != 0x00000000 : bool)
  Class: Eq_706
  DataType: bool
  OrigDataType: bool
T_707: (in r4_41 : int32)
  Class: Eq_701
  DataType: int32
  OrigDataType: word32
T_708: (in 0x00000000 : word32)
  Class: Eq_701
  DataType: int32
  OrigDataType: word32
T_709: (in pc_69 : word32)
  Class: Eq_709
  DataType: word32
  OrigDataType: word32
T_710: (in r3_72 : word32)
  Class: Eq_710
  DataType: word32
  OrigDataType: word32
T_711: (in 0x00000000 : word32)
  Class: Eq_711
  DataType: word32
  OrigDataType: word32
T_712: (in r5_25 + 0x00000000 : word32)
  Class: Eq_712
  DataType: (ptr32 (ptr32 (ptr32 (ptr32 (ptr32 code)))))
  OrigDataType: (union ((ptr32 (ptr32 (ptr32 (ptr32 (ptr32 code))))) u1) (ptr32 u0))
T_713: (in Mem18[r5_25 + 0x00000000:word32] : word32)
  Class: Eq_713
  DataType: (ptr32 code)
  OrigDataType: (ptr32 code)
T_714: (in r6_38 != r4_41 : bool)
  Class: Eq_714
  DataType: bool
  OrigDataType: bool
T_715:
  Class: Eq_715
  DataType: word64
  OrigDataType: (struct 0008 (0 T_470 t0000))
T_716:
  Class: Eq_716
  DataType: word64
  OrigDataType: (struct 0008 (0 T_480 t0000))
*/
typedef struct Globals {
	int32 dw107D0;	// 107D0
	int32 dw107D4;	// 107D4
	word32 dw107F8;	// 107F8
	word32 dw107FC;	// 107FC
	<anonymous> * ptr10800;	// 10800
	word32 dw10830;	// 10830
	word32 dw10834;	// 10834
	<anonymous> * ptr10838;	// 10838
	byte * ptr10860;	// 10860
	word32 dw10D68;	// 10D68
	word64 (* ptr11220)[];	// 11220
	word64 (* ptr11274)[];	// 11274
	Eq_498 t112C8;	// 112C8
	Eq_498 t112D0;	// 112D0
	struct Eq_523 * ptr11550;	// 11550
	Eq_498 t11720;	// 11720
	real32 r117F8;	// 117F8
	<anonymous> **** ptr118F4;	// 118F4
	<anonymous> ***** ptr11934;	// 11934
	int32 dw11938;	// 11938
	<anonymous> * ptr2200C;	// 2200C
	<anonymous> * ptr22010;	// 22010
	<anonymous> * ptr22014;	// 22014
	<anonymous> * ptr22018;	// 22018
	<anonymous> * ptr2201C;	// 2201C
	<anonymous> * ptr22020;	// 22020
	<anonymous> * ptr22024;	// 22024
	<anonymous> * ptr22028;	// 22028
	<anonymous> * ptr2202C;	// 2202C
	<anonymous> * ptr22030;	// 22030
	<anonymous> * ptr22034;	// 22034
	<anonymous> * ptr22038;	// 22038
	<anonymous> * ptr2203C;	// 2203C
	<anonymous> * ptr22040;	// 22040
	<anonymous> * ptr22044;	// 22044
	<anonymous> * ptr22048;	// 22048
	<anonymous> * ptr2204C;	// 2204C
	<anonymous> * ptr22050;	// 22050
	<anonymous> * ptr22054;	// 22054
	<anonymous> * ptr22058;	// 22058
	<anonymous> * ptr2205C;	// 2205C
} Eq_1;

typedef code * (Eq_3)(code *);

typedef void (Eq_47)();

typedef void (Eq_50)();

typedef void (Eq_115)(code *);

typedef void (Eq_123)(code *);

typedef void (Eq_126)();

typedef void (Eq_129)();

typedef void (Eq_132)();

typedef void (Eq_135)();

typedef void (Eq_138)(word32);

typedef void (Eq_143)(word32);

typedef word32 (Eq_146)(word32);

typedef void (Eq_151)();

typedef void (Eq_154)();

typedef void (Eq_158)();

typedef void (Eq_161)();

typedef void (Eq_171)();

typedef void (Eq_188)();

typedef void (Eq_201)();

typedef void (Eq_204)();

typedef word32 (Eq_207)();

typedef void (Eq_235)();

typedef void (Eq_241)(word32);

typedef void (Eq_244)();

typedef void (Eq_249)();

typedef void (Eq_274)();

typedef void (Eq_280)();

typedef void (Eq_313)();

typedef void (Eq_316)();

typedef void (Eq_366)(word32);

typedef void (Eq_420)();

typedef void (Eq_423)();

typedef void (Eq_472)();

typedef void (Eq_481)();

typedef  * (Eq_484)(Eq_486);

typedef union Eq_486 {
	real64 u0;
	word128 u1;
	word32 u2;
} Eq_486;

typedef Eq_486 (Eq_489)();

typedef real64[1] (Eq_495)(Eq_486, Eq_498);

typedef union Eq_498 {
	word64 u0;
	word32 u1;
} Eq_498;

typedef void (Eq_512)();

typedef void (Eq_515)();

typedef word64[1] (Eq_518)(word64, word64);

typedef struct Eq_523 {
	word64 qw0000;	// 0
	word64 qw0010;	// 10
} Eq_523;

typedef void (Eq_535)();

typedef void (Eq_607)();

typedef void (Eq_632)();

typedef void (Eq_635)(Eq_486);

typedef word128 (Eq_639)();

typedef union Eq_692 {
	int32 u0;
	ptr32 u1;
} Eq_692;

typedef word32 (Eq_698)(code *);

