// finalassignment.globals.c
// Generated by decompiling finalassignment
// using Reko decompiler version 0.9.0.0.

#include "finalassignment.h"

int32 g_dw107D0 = 71740;
int32 g_dw107D4 = 96;
word32 g_dw107F8 = 0x00022080;
word32 g_dw107FC = 0x00022080;
<anonymous> * g_ptr10800 = null;
word32 g_dw10830 = 0x00022080;
word32 g_dw10834 = 0x00022080;
<anonymous> * g_ptr10838 = null;
byte * g_ptr10860 = &g_b22080;
word32 g_dw10D68 = 0x00011A24;
word64 (* g_ptr11220)[] = &g_a22070;
word64 (* g_ptr11274)[] = &g_a22070;
Eq_498 g_t112C8 = 
	{
		0x401921FB54442D18
	};
Eq_498 g_t112D0 = 
	{
		0x4034000000000000
	};
struct Eq_523 * g_ptr11550 = &g_a22070;
Eq_498 g_t11720 = 
	{
		0x40E0BF8000000000
	};
real32 g_r117F8 = 0.0F;
<anonymous> **** g_ptr118F4 = &g_ptrE0466005;
<anonymous> ***** g_ptr11934 = &g_ptr10610;
int32 g_dw11938 = 67080;
<anonymous> * g_ptr2200C = &g_t10668;
<anonymous> * g_ptr22010 = &g_t10668;
<anonymous> * g_ptr22014 = &g_t10668;
<anonymous> * g_ptr22018 = &g_t10668;
<anonymous> * g_ptr2201C = &g_t10668;
<anonymous> * g_ptr22020 = &g_t10668;
<anonymous> * g_ptr22024 = &g_t10668;
<anonymous> * g_ptr22028 = &g_t10668;
<anonymous> * g_ptr2202C = &g_t10668;
<anonymous> * g_ptr22030 = &g_t10668;
<anonymous> * g_ptr22034 = &g_t10668;
<anonymous> * g_ptr22038 = &g_t10668;
<anonymous> * g_ptr2203C = &g_t10668;
<anonymous> * g_ptr22040 = &g_t10668;
<anonymous> * g_ptr22044 = &g_t10668;
<anonymous> * g_ptr22048 = &g_t10668;
<anonymous> * g_ptr2204C = &g_t10668;
<anonymous> * g_ptr22050 = &g_t10668;
<anonymous> * g_ptr22054 = &g_t10668;
<anonymous> * g_ptr22058 = &g_t10668;
<anonymous> * g_ptr2205C = &g_t10668;
byte g_b22080 = 0x00;
word64 g_a22070[] = 
	{
	};
<anonymous> *** g_ptrE0466005;
<anonymous> **** g_ptr10610 = &g_ptr0216;
<anonymous> g_t10668 = <code>;
<anonymous> *** g_ptr0216;

